class_name QuestsDb
# Rantai quest per lantai — urutan jelas, satu aktif dalam satu waktu.
# kind: "moved", "kill", "clear_floor", "reach_room", "boss_kill",
#       "open_chest", "descend", "custom"
# need: jumlah untuk kind berhitung (kill/reach_room); 0/1 utk toggle.

static func is_boss_floor(floor_num: int) -> bool:
	return floor_num % 5 == 0


static func for_floor(floor_num: int, room_count: int, n_elites: int = 0) -> Array:
	var steps: Array = []
	if floor_num == 1:
		steps.append({"title": "Awaken", "desc": "Move — tilt the left stick", "kind": "moved", "need": 1})
		steps.append({"title": "Sweep", "desc": "Clear %d rooms of skeletons" % room_count, "kind": "clear_floor", "need": room_count})
		steps.append({"title": "First Spoils", "desc": "Open the treasure chest at the floor's end", "kind": "open_chest", "need": 1})
		steps.append({"title": "Descend", "desc": "Tap the screen to descend to Floor 2", "kind": "descend", "need": 1})
	elif is_boss_floor(floor_num):
		steps.append({"title": "Throne Room", "desc": "Fight through to the last room of this floor", "kind": "reach_room", "need": room_count - 1})
		steps.append({"title": "Bone King", "desc": "Defeat the Throne's ruler", "kind": "boss_kill", "need": 1})
		steps.append({"title": "The Crown", "desc": "Claim the King's spoils chest", "kind": "open_chest", "need": 1})
		steps.append({"title": "Descend", "desc": "Tap to descend deeper", "kind": "descend", "need": 1})
	else:
		if floor_num >= 3 and n_elites > 0:
			var n_hunt := mini(n_elites, 2)
			steps.append({"title": "Elite Hunter", "desc": "Slay %d crimson elite%s" % [n_hunt, "s" if n_hunt > 1 else ""], "kind": "elite_kill", "need": n_hunt})
		if floor_num >= 4:
			if floor_num % 2 == 0:
				steps.append({"title": "Gem Rush", "desc": "Absorb 6 soul gems", "kind": "gem", "need": 6})
			else:
				steps.append({"title": "Battle Frenzy", "desc": "Reach a x8 kill combo", "kind": "combo", "need": 1})
				if Stats.floor_num >= 10:
					steps.append({"title": "Crescendo", "desc": "Reach a x40 kill combo", "kind": "combo40", "need": 1})
		if floor_num >= 6:
			steps.append({"title": "Skillful Hands", "desc": "Unleash 2 skills", "kind": "skill", "need": 2})
		if floor_num >= 8 and floor_num % 4 == 3:
			steps.append({"title": "Grave Robbing", "desc": "Smash 2 bone urns", "kind": "urn", "need": 2})
		if floor_num >= 13 and floor_num % 4 == 1:
			steps.append({"title": "Porcelain Storm", "desc": "Smash 4 bone urns", "kind": "urn", "need": 4})
		if floor_num >= 10 and floor_num % 4 == 2:
			steps.append({"title": "Gaoler Breaker", "desc": "Slay 2 faceless Gaolers", "kind": "gaoler_kill", "need": 2})
		if floor_num >= 12 and floor_num % 4 == 0:
			steps.append({"title": "Dead Letters", "desc": "Read the lore stone on this floor", "kind": "page", "need": 1})
		if floor_num >= 11 and floor_num % 4 == 3:
			steps.append({"title": "Frenzied", "desc": "Trigger a RAMPAGE (3 kills in 2.5s)", "kind": "rampage", "need": 1})
		if floor_num >= 5 and floor_num % 4 == 1:
			steps.append({"title": "Siege Breaker", "desc": "Topple 2 Bone Sentinels", "kind": "sentinel_kill", "need": 2})
		if floor_num >= 6 and floor_num % 4 == 2:
			steps.append({"title": "Hammer of Dawn", "desc": "Land a HEAVY attack", "kind": "heavy", "need": 1})
		if floor_num >= 4 and floor_num % 5 == 4:
			steps.append({"title": "Soul Bargainer", "desc": "Strike a deal with Mahzan", "kind": "mahzan", "need": 1})
		if floor_num >= 6 and floor_num % 5 == 1:
			steps.append({"title": "Hex Plunderer", "desc": "Open a CURSED CHEST", "kind": "cursed_chest", "need": 1})
		if floor_num >= 7 and floor_num % 4 == 3:
			steps.append({"title": "Phantom Hunt", "desc": "Slay 2 Shades", "kind": "shade_kill", "need": 2})
		if floor_num >= 7 and floor_num % 4 == 0:
			steps.append({"title": "Curse Silencer", "desc": "Slay 2 Hex Priests", "kind": "hexer_kill", "need": 2})
		if floor_num >= 7 and floor_num % 3 == 1:
			steps.append({"title": "Ghost Dancer", "desc": "Dash through 2 attacks at the last instant", "kind": "pdodge", "need": 2})
			steps.append({"title": "Shadow Waltz", "desc": "Perfect-dodge 3 attacks this run (0/3)", "kind": "pdodge_run", "need": 3})
		if floor_num >= 17 and floor_num % 4 == 2:
			steps.append({"title": "Tempest Herald", "desc": "Unleash a SOUL STORM", "kind": "storm", "need": 1})
		if floor_num >= 8 and floor_num % 4 == 1:
			steps.append({"title": "Thorn Proof", "desc": "Slay 2 Spiked Cadavers", "kind": "spiker_kill", "need": 2})
		if floor_num >= 5 and floor_num % 4 == 2:
			steps.append({"title": "Trap Dancer", "desc": "Defuse 3 traps while they sleep", "kind": "trap_disarm", "need": 3})
		if floor_num >= 8 and floor_num % 5 == 3:
			steps.append({"title": "Hoard Diver", "desc": "Crack a GILDED chest", "kind": "gilded_chest", "need": 1})
		if floor_num >= 7 and floor_num % 5 == 4:
			steps.append({"title": "Dark Watch", "desc": "Slay 2 Dwellers after they reveal", "kind": "lurker_kill", "need": 2})
		if floor_num >= 6 and floor_num % 4 == 0:
			steps.append({"title": "Ghost Hunter", "desc": "Catch 2 wandering wisps", "kind": "wisp", "need": 2})
		if floor_num >= 7 and floor_num % 5 == 2:
			steps.append({"title": "Purge", "desc": "Smash the Dread Obelisk", "kind": "obelisk", "need": 1})
		if floor_num >= 22 and floor_num % 4 == 1:
			steps.append({"title": "Toll Keeper", "desc": "Unleash the REAPER'S TOLL", "kind": "rites", "need": 1})
	if Stats.floor_num >= 22 and Stats.floor_num % 5 == 3:
		steps.append({"title": "Earthshaker", "desc": "Slam the floor — strike & stun foes with SEISMIC", "kind": "seismic", "need": 1})
	if Stats.floor_num >= 8 and Stats.floor_num % 6 == 0:
		steps.append({"title": "Grief Silencer", "desc": "Silence 2 Wailing Maidens", "kind": "maiden_kill", "need": 2})
	if Stats.floor_num >= 6 and Stats.floor_num % 7 == 3:
		steps.append({"title": "Grave Denier", "desc": "Shatter 2 Revenant tombstones", "kind": "tomb", "need": 2})
	if Stats.floor_num >= 25 and Stats.floor_num % 5 == 0:
		steps.append({"title": "Crown's Edge", "desc": "Unleash KINGSFALL on the throne floor", "kind": "kingsfall", "need": 1})
	if Stats.floor_num >= 6 and Stats.floor_num % 5 == 3:
		steps.append({"title": "Grave Etiquette", "desc": "Hold a prayer over a blood stain (0/1)", "kind": "pray", "need": 1})
	if Stats.floor_num >= 8 and Stats.floor_num % 6 == 4:
		steps.append({"title": "Firefly Hunt", "desc": "Catch three wandering wisps (0/3)", "kind": "wisp", "need": 3})
	if Stats.floor_num >= 13 and Stats.floor_num % 7 == 1:
		steps.append({"title": "Commuter of the Dead", "desc": "Let the Ferryman carry you (0/1)", "kind": "ferry", "need": 1})
	if Stats.floor_num >= 14 and Stats.floor_num % 8 == 6:
		steps.append({"title": "Shattered Glass", "desc": "Slay 2 MIRRORHIDE elites (0/2)", "kind": "affix_mirrorhide", "need": 2})
		steps.append({"title": "Sentence Passed", "desc": "Slay 5 foes with King's Gavel (0/5)", "kind": "kill_king_gavel", "need": 5})
		steps.append({"title": "Current Breaker", "desc": "Slay 2 TIDEBOUND elites (0/2)", "kind": "affix_tidebound", "need": 2})
		steps.append({"title": "Tar Scraper", "desc": "Slay 4 TARRED elites (0/4)", "kind": "affix_tarred", "need": 4})
		steps.append({"title": "Rot Cutter", "desc": "Slay 4 BLOATED elites (0/4)", "kind": "affix_bloated", "need": 4})
		steps.append({"title": "Hooked", "desc": "Slay 5 foes with Keelhook (0/5)", "kind": "kill_keelhook", "need": 5})
		steps.append({"title": "Cull Picker", "desc": "Clear 2 HALFWAY DEAD floors (0/2)", "kind": "cullwalk", "need": 2})
		steps.append({"title": "True Bearing", "desc": "Slay 5 foes with Sextant Edge (0/5)", "kind": "kill_sextant_edge", "need": 5})
		steps.append({"title": "Rust Doctor", "desc": "Slay 4 Rust Saws (0/4)", "kind": "saw_kill", "need": 4})
		steps.append({"title": "Eel Sauce", "desc": "Slay 4 Wrack Eels (0/4)", "kind": "eel_kill", "need": 4})
		steps.append({"title": "Hook Dodger", "desc": "Slay 4 Hookfins (0/4)", "kind": "hookfin_kill", "need": 4})
		steps.append({"title": "Death Chaplain", "desc": "Slay a Gutter Chaplain, a Bell Warden and a Salt Leech in one run", "kind": "chaplain_kill", "need": 2})
		steps.append({"title": "Vein Tapping", "desc": "Clear 2 RICH VEIN floors (0/2)", "kind": "veinwalk", "need": 2})
		steps.append({"title": "Lamp Keeper", "desc": "Clear 2 PILOT LIGHT floors (0/2)", "kind": "pilotwalk", "need": 2})
		steps.append({"title": "Wretched Luck", "desc": "Slay 4 Keel Wretches (0/4)", "kind": "wretch_kill", "need": 4})
		steps.append({"title": "Turned Round", "desc": "Clear 2 WIDDERSHINS floors (0/2)", "kind": "widderwalk", "need": 2})
		steps.append({"title": "Wight Watching", "desc": "Slay 4 Gunnel Wights (0/4)", "kind": "wight_kill", "need": 4})
		steps.append({"title": "Rat Catching", "desc": "Slay 8 Bilge Rats (0/8)", "kind": "rat_kill", "need": 8})
		steps.append({"title": "Disarm the Fuse", "desc": "Slay 4 Powder Monkeys (0/4)", "kind": "monkey_kill", "need": 4})
		steps.append({"title": "Shell Cracker", "desc": "Slay 5 Fathom Crabs (0/5)", "kind": "crab_kill", "need": 5})
		steps.append({"title": "Last Rites", "desc": "Slay 4 Quarter Ghosts (0/4)", "kind": "ghost_kill", "need": 4})
		steps.append({"title": "Uncoil", "desc": "Slay 6 Salt Eels (0/6)", "kind": "salteel_kill", "need": 6})
		steps.append({"title": "Pull the Wall Down", "desc": "Slay 3 Deck Brutes (0/3)", "kind": "brute_kill", "need": 3})
		steps.append({"title": "Calm Seas", "desc": "Fell 4 Bilge Furies before their frenzy peaks (0/4)", "kind": "fury_kill", "need": 4})
		steps.append({"title": "Defrocked", "desc": "Slay 4 Salt Liches (0/4)", "kind": "lich_kill", "need": 4})
		steps.append({"title": "Herald's Due", "desc": "Slay 5 Foam Heralds (0/5)", "kind": "herald_kill", "need": 5})
		steps.append({"title": "Sprite Pest", "desc": "Slay 6 Salt Sprites (0/6)", "kind": "sprite_kill", "need": 6})
		steps.append({"title": "Union Buster", "desc": "Slay 4 Bilge Smiths (0/4)", "kind": "smith_kill", "need": 4})
		steps.append({"title": "Still Water", "desc": "Clear 2 SLACK WATER floors (0/2)", "kind": "slackwalk", "need": 2})
		steps.append({"title": "Lucky Wind", "desc": "Clear 2 SALVAGE BREEZE floors (0/2)", "kind": "breezewalk", "need": 2})
		steps.append({"title": "Salved", "desc": "Clear 2 DEEP SALVE floors (0/2)", "kind": "salvewalk", "need": 2})
		steps.append({"title": "Hull's Ghost", "desc": "Clear 2 KEEL SPIRIT floors (0/2)", "kind": "spiritwalk", "need": 2})
		steps.append({"title": "Light Carrier", "desc": "Clear 2 LANTERN WAKE floors (0/2)", "kind": "wakewalk", "need": 2})
		steps.append({"title": "Through the Murk", "desc": "Clear 2 FOG BANK floors (0/2)", "kind": "fogwalk", "need": 2})
		steps.append({"title": "Slow Hours", "desc": "Clear 2 TIDE CLOCK floors (0/2)", "kind": "clockwalk", "need": 2})
		steps.append({"title": "Well Walker", "desc": "Clear 2 DEEP WELL floors (0/2)", "kind": "wellwalk", "need": 2})
		steps.append({"title": "Dead Calm", "desc": "Clear 2 BILGE STILL floors (0/2)", "kind": "stillwalk", "need": 2})
		steps.append({"title": "Sounding the Deep", "desc": "Clear 2 KEEL GROAN floors (0/2)", "kind": "groanwalk", "need": 2})
		steps.append({"title": "Rode the Gale", "desc": "Clear 2 SALTWIND floors (0/2)", "kind": "windwalk", "need": 2})
		steps.append({"title": "Lantern Bearer", "desc": "Clear 2 BONE LANTERN floors (0/2)", "kind": "lanternwalk2", "need": 2})
		steps.append({"title": "Paid Her Due", "desc": "Clear 2 DEAD RECKONING floors (0/2)", "kind": "reckonwalk", "need": 2})
		steps.append({"title": "Lights Out", "desc": "Clear 2 GLOOM TIDE floors (0/2)", "kind": "gloomwalk", "need": 2})
		steps.append({"title": "Wake Watcher", "desc": "Clear 2 PALE WAKE floors (0/2)", "kind": "wakewalk", "need": 2})
		steps.append({"title": "Rose from the Bottom", "desc": "Clear 2 MURK LIFT floors (0/2)", "kind": "murkwalk", "need": 2})
		steps.append({"title": "Plugged Ears", "desc": "Clear 2 SIREN HUM floors (0/2)", "kind": "humwalk", "need": 2})
		steps.append({"title": "Free the Taken", "desc": "Slay 6 Siren Thralls (0/6)", "kind": "thrall_kill", "need": 6})
		steps.append({"title": "Still Water Runs Deep", "desc": "Clear 2 GRIM CALM floors (0/2)", "kind": "grimwalk", "need": 2})
		steps.append({"title": "Wick Snuffer", "desc": "Snuff 5 Pale Lanterns (0/5)", "kind": "lantern_kill", "need": 5})
		steps.append({"title": "Off the Rails", "desc": "Slay 5 Gunnel Fiends (0/5)", "kind": "gunnel_kill", "need": 5})
		steps.append({"title": "Hauled Under", "desc": "Clear 2 KEEL HAUL floors (0/2)", "kind": "haulwalk", "need": 2})
		steps.append({"title": "Break the Tempo", "desc": "Silence 4 Bilge Cantors (0/4)", "kind": "bice_kill", "need": 4})
		steps.append({"title": "Dry Your Eyes", "desc": "Clear 2 WEEPING TIDE floors (0/2)", "kind": "tearwalk", "need": 2})
		steps.append({"title": "Low Water Mark", "desc": "Clear 2 DEEP DRAUGHT floors (0/2)", "kind": "keelwalk", "need": 2})
		steps.append({"title": "Sapper", "desc": "Slay 5 POWDERKEG elites (0/5)", "kind": "keg_kill", "need": 5})
		steps.append({"title": "Wade Through It", "desc": "Clear 2 THICK TIDE floors (0/2)", "kind": "thickwalk", "need": 2})
		steps.append({"title": "Take the Strain", "desc": "Clear 2 SLACK LINE floors (0/2)", "kind": "linewalk", "need": 2})
		steps.append({"title": "Dim the Wick", "desc": "Clear 2 LOW LANTERN floors (0/2)", "kind": "wickwalk", "need": 2})
		steps.append({"title": "Mirage Turner", "desc": "Survive a MIRAGE SEA floor (0/1)", "kind": "miragewalk", "need": 1})
		steps.append({"title": "Light Sleeper", "desc": "Clear 2 BILGE LULL floors (0/2)", "kind": "lullwalk", "need": 2})
		steps.append({"title": "Quash the Warrant", "desc": "Slay 6 Tide Bailiffs (0/6)", "kind": "bailiff_kill", "need": 6})
		steps.append({"title": "Skim the Foam", "desc": "Slay 8 Salt Skimmers (0/8)", "kind": "skimmer_kill", "need": 8})
		steps.append({"title": "Break the Litany", "desc": "Slay 5 Brine Monks (0/5)", "kind": "monk_kill", "need": 5})
		steps.append({"title": "Cut the Line", "desc": "Slay 4 Deck Riggers (0/4)", "kind": "rigger_kill", "need": 4})
		steps.append({"title": "Sky Blind", "desc": "Slay 5 Dread Gulls (0/5)", "kind": "gull_kill", "need": 5})
		steps.append({"title": "Still the Air", "desc": "Slay 4 Gale Singers (0/4)", "kind": "gale_kill", "need": 4})
		steps.append({"title": "Widow's Tithe", "desc": "Slay 4 Snatch Widows (0/4)", "kind": "snatch_kill", "need": 4})
		steps.append({"title": "Swat Team", "desc": "Slay 12 Gunnel Gnats (0/12)", "kind": "gnat_kill", "need": 12})
		steps.append({"title": "Break the Pulpit", "desc": "Slay 4 Deck Reverends (0/4)", "kind": "reverend_kill", "need": 4})
		steps.append({"title": "Topple the Mast", "desc": "Slay 3 Mast Lurchers (0/3)", "kind": "lurcher_kill", "need": 3})
		steps.append({"title": "Fogwader", "desc": "Reach the exit through bilge fog (0/1)", "kind": "fogwade", "need": 1})
		steps.append({"title": "Still the Dirge", "desc": "Slay 3 Dirge Singers (0/3)", "kind": "dirge_kill", "need": 3})
		steps.append({"title": "Mutiny's End", "desc": "Slay 2 Boatswains (0/2)", "kind": "boatswain_kill", "need": 2})
		steps.append({"title": "Leechwader", "desc": "Reach the exit through leech tide (0/1)", "kind": "leechwade", "need": 1})
		steps.append({"title": "Grate Hopper", "desc": "Ride 3 fathom grates (0/3)", "kind": "grate_hop", "need": 3})
		steps.append({"title": "Lights Out", "desc": "Slay 4 Gloom Lanterns (0/4)", "kind": "gloom_kill", "need": 4})
		steps.append({"title": "Icebreaker", "desc": "Survive a Rime Tide floor (0/1)", "kind": "rimewade", "need": 1})
		steps.append({"title": "Matador", "desc": "Survive a Bull Tide floor (0/1)", "kind": "bullwade", "need": 1})
		steps.append({"title": "Unseen Walker", "desc": "Survive a Hollow Watch floor (0/1)", "kind": "hollowwatch", "need": 1})
		steps.append({"title": "Windwalker", "desc": "Survive a Gale Weather floor (0/1)", "kind": "galeweather", "need": 1})
		steps.append({"title": "Glutton's Harvest", "desc": "Survive a Soul-Glut floor (0/1)", "kind": "soulglut", "need": 1})
		steps.append({"title": "Rustproof", "desc": "Survive a Rust Rain floor (0/1)", "kind": "rustrain", "need": 1})
		steps.append({"title": "Dead Calm", "desc": "Survive a Still Tide floor (0/1)", "kind": "stilltide", "need": 1})
		steps.append({"title": "Shallow Wake", "desc": "Survive a Pale Draught floor (0/1)", "kind": "paledraught", "need": 1})
		steps.append({"title": "Stopped Time", "desc": "Survive a Pale Clock floor (0/1)", "kind": "paleclock", "need": 1})
		steps.append({"title": "Light's Out", "desc": "Survive a Pale Wick floor (0/1)", "kind": "palewick", "need": 1})
		steps.append({"title": "Mad Waters", "desc": "Survive a Crazed Sea floor (0/1)", "kind": "crazedsea", "need": 1})
		steps.append({"title": "Brined Bones", "desc": "Survive an Old Salt Tide floor (0/1)", "kind": "oldsalttide", "need": 1})
		steps.append({"title": "Gilded Wake", "desc": "Survive a Golden Hour floor (0/1)", "kind": "goldenhour", "need": 1})
		steps.append({"title": "Salvage Law", "desc": "Survive a Salvage Rights floor (0/1)", "kind": "salvagerights", "need": 1})
		steps.append({"title": "Wake Watcher", "desc": "Survive a Green Wake floor (0/1)", "kind": "greenwake", "need": 1})
		steps.append({"title": "Chime Breaker", "desc": "Ring out 3 bellchime elites (0/3)", "kind": "affix_bellchime", "need": 3})
		steps.append({"title": "Brood Stiller", "desc": "Fell 3 Brood Keels (0/3)", "kind": "broodkill", "need": 3})
		steps.append({"title": "Iron Keel", "desc": "Survive an Iron Sea floor (0/1)", "kind": "ironsea", "need": 1})
		steps.append({"title": "Hag Drowner", "desc": "Silence 3 Brine Hags (0/3)", "kind": "hagkill", "need": 3})
		steps.append({"title": "Riptide Runner", "desc": "Fell 3 riptorn elites (0/3)", "kind": "affix_riptorn", "need": 3})
		steps.append({"title": "Sea-Tithe", "desc": "Collect from a tithed elite's fall (0/1)", "kind": "affix_tithed", "need": 1})
		steps.append({"title": "Spill the Purse", "desc": "Split a soulspill elite's purse (0/1)", "kind": "affix_soulspill", "need": 1})
		steps.append({"title": "Break the Hull", "desc": "Fell 2 mossback elites (0/2)", "kind": "affix_mossback", "need": 2})
		steps.append({"title": "Silence the Jeer", "desc": "Slay 3 Jeerjacks (0/3)", "kind": "jeerkill", "need": 3})
		steps.append({"title": "Lull Walker", "desc": "Wade a Gloom Lull (0/1)", "kind": "gloomlull", "need": 1})
		steps.append({"title": "Glass Sights", "desc": "Wade a Soul Glass tide (0/1)", "kind": "soulglass", "need": 1})
		steps.append({"title": "Fog Walker", "desc": "Wade a Grave Fog tide (0/1)", "kind": "gravefog", "need": 1})
		steps.append({"title": "Glow Wader", "desc": "Wade a Bilge Glow tide (0/1)", "kind": "bilgeglow", "need": 1})
		steps.append({"title": "Ragged Runner", "desc": "Clear a Run Ragged floor (0/1)", "kind": "runragged", "need": 1})
		steps.append({"title": "Feast Warden", "desc": "Clear a Feast Tide floor (0/1)", "kind": "feasttide", "need": 1})
		steps.append({"title": "Deck Sweeper", "desc": "Slay 10 foes on this floor (0/10)", "kind": "kill", "need": 10})
		steps.append({"title": "Snare Snuffer", "desc": "Trip a keel snare trap (0/1)", "kind": "keel_snare", "need": 1})
		steps.append({"title": "Purse Diver", "desc": "Clear a Purse Tide floor (0/1)", "kind": "pursetide", "need": 1})
		steps.append({"title": "Hollow Swimmer", "desc": "Clear a Hollow Tide floor (0/1)", "kind": "hollowtide", "need": 1})
		steps.append({"title": "Dowager's Debt", "desc": "Clear a Widow's Due floor (0/1)", "kind": "widowsdue", "need": 1})
		steps.append({"title": "Fog Walker", "desc": "Clear a Salt Fog floor (0/1)", "kind": "saltfog", "need": 1})
		steps.append({"title": "Moonlighter", "desc": "Clear a Bilge Moon floor (0/1)", "kind": "bilgemoon", "need": 1})
		steps.append({"title": "Take the House", "desc": "Clear a Dead Man's Deck floor (0/1)", "kind": "deadmansdeck", "need": 1})
		steps.append({"title": "Coin of the Realm", "desc": "Clear a Brass Tide floor (0/1)", "kind": "brasstide", "need": 1})
		steps.append({"title": "Balanced Books", "desc": "Clear a Deep Ledger floor (0/1)", "kind": "deepledger", "need": 1})
		steps.append({"title": "Purse Guard", "desc": "Clear a floor holding 50+ souls (0/1)", "kind": "rich_floor", "need": 1})
		steps.append({"title": "Ride the Wake", "desc": "Clear a Keel Wake floor (0/1)", "kind": "keelwake", "need": 1})
		steps.append({"title": "Half Awake", "desc": "Clear a Siren's Lull floor (0/1)", "kind": "sirenslull", "need": 1})
		steps.append({"title": "Downwind", "desc": "Clear a Foul Wind floor (0/1)", "kind": "foulwind", "need": 1})
		steps.append({"title": "Ride the Ring", "desc": "Clear a Keel Ripple floor (0/1)", "kind": "keelripple", "need": 1})
		steps.append({"title": "Ghost Sail", "desc": "Clear a Pale Drift floor (0/1)", "kind": "paledrift", "need": 1})
		steps.append({"title": "Swell Rider", "desc": "Clear a Deep Swell floor (0/1)", "kind": "deepswell", "need": 1})
		steps.append({"title": "Syrup Waltz", "desc": "Clear a Thick Water floor (0/1)", "kind": "thickwater", "need": 1})
		steps.append({"title": "Weight of Souls", "desc": "Slay 4 Soulheavy brutes (0/4)", "kind": "affix_soulheavy", "need": 4})
		steps.append({"title": "Pin the Wind", "desc": "Slay 6 Mistral Imps (0/6)", "kind": "mistralimp_kill", "need": 6})
		steps.append({"title": "Gale Runner", "desc": "Clear a Pale Gale floor (0/1)", "kind": "palegale", "need": 1})
		steps.append({"title": "Four Knells", "desc": "Swear 4 omens across a run (0/4)", "kind": "omen_sworn", "need": 4})
		steps.append({"title": "Reap the Pale", "desc": "Clear a Pale Harvest floor (0/1)", "kind": "paleharvest", "need": 1})
		steps.append({"title": "Trim the Wick", "desc": "Clear a Grim Lantern floor (0/1)", "kind": "grimlantern", "need": 1})
		steps.append({"title": "Still the Swell", "desc": "Clear a Salt Lull floor (0/1)", "kind": "saltlull", "need": 1})
		steps.append({"title": "Gilded Watch", "desc": "Clear a Keelglow floor (0/1)", "kind": "keelglow", "need": 1})
		steps.append({"title": "Salvage Diver", "desc": "Clear 2 Pale Salvage floors (0/2)", "kind": "palesalvage", "need": 2})
		steps.append({"title": "Silence the Sermon", "desc": "Slay 5 Bilge Priors (0/5)", "kind": "bilgeprior_kill", "need": 5})
		steps.append({"title": "Crack the Plating", "desc": "Crack 8 grimhull-plated foes (0/8)", "kind": "affix_grimhull", "need": 8})
		steps.append({"title": "Cull the Wrought", "desc": "Fell 6 grimwrought elites (0/6)", "kind": "affix_grimwrought", "need": 6})
		steps.append({"title": "Crack the Shell", "desc": "Claim the souls inside 6 soulshell elites (0/6)", "kind": "affix_soulshell", "need": 6})
		steps.append({"title": "Ring the Knell", "desc": "Silence 6 tollbound elites (0/6)", "kind": "affix_tollbound", "need": 6})
		steps.append({"title": "Cut the Lines", "desc": "Unmoor 5 deckbound elites (0/5)", "kind": "affix_deckbound", "need": 5})
		steps.append({"title": "Unburden the Dead", "desc": "Fell 5 pallbearers (0/5)", "kind": "pallbearer_kill", "need": 5})
		steps.append({"title": "Close the Graveyard", "desc": "Fell 4 keel sextons (0/4)", "kind": "keelsexton_kill", "need": 4})
		steps.append({"title": "Break the Chains", "desc": "Fell 5 chain wardens (0/5)", "kind": "chainwarden_kill", "need": 5})
		steps.append({"title": "Defrock the Curate", "desc": "Fell 4 salt curates (0/4)", "kind": "curate_kill", "need": 4})
		steps.append({"title": "Quiet the Procession", "desc": "Fell 4 keel vergers (0/4)", "kind": "verger_kill", "need": 4})
		steps.append({"title": "Drink the Grey", "desc": "Pray beneath 2 Grey Tides (0/2)", "kind": "greytide", "need": 2})
		steps.append({"title": "Silence the Litany", "desc": "Cut 3 Deep Chaplains short (0/3)", "kind": "dchaplain_kill", "need": 3})
		steps.append({"title": "Ride the Current", "desc": "Clear 2 Pale Current floors (0/2)", "kind": "palecurrent", "need": 2})
		steps.append({"title": "Still the Bell", "desc": "Silence 3 Grey Sextons (0/3)", "kind": "sexton_kill", "need": 3})
		steps.append({"title": "Dry the Veil", "desc": "End 3 Deep Widows' mourning (0/3)", "kind": "dwidow_kill", "need": 3})
		steps.append({"title": "Walk the White", "desc": "Clear 2 Crest Line floors (0/2)", "kind": "crestline", "need": 2})
		steps.append({"title": "Sink the Crossing", "desc": "Drown 3 Pale Ferrymen (0/3)", "kind": "ferryman_kill", "need": 3})
		steps.append({"title": "Still the Matron", "desc": "Silence 2 Keel Widows (0/2)", "kind": "kwidow_kill", "need": 2})
		steps.append({"title": "Pay the Toll", "desc": "Endure 2 Keel Toll tides (0/2)", "kind": "keeltoll", "need": 2})
		steps.append({"title": "Close the Ledger", "desc": "Endure 2 Deep Tally tides (0/2)", "kind": "deeptally", "need": 2})
		steps.append({"title": "Outrun the Toll", "desc": "Survive 2 Wake Toll tides (0/2)", "kind": "waketoll", "need": 2})
		steps.append({"title": "Ride the Crest", "desc": "Endure 2 Crest Toll tides (0/2)", "kind": "cresttoll", "need": 2})
		steps.append({"title": "Follow the Wake", "desc": "Endure 2 Deep Wake tides (0/2)", "kind": "deepwake", "need": 2})
		steps.append({"title": "Audit the Tally", "desc": "Endure 2 Pale Tally tides (0/2)", "kind": "paletally", "need": 2})
		steps.append({"title": "Pass the Audit", "desc": "Endure 2 Pale Audit tides (0/2)", "kind": "paleaudit", "need": 2})
		steps.append({"title": "Take the Mending", "desc": "Endure 2 Grey Mend tides (0/2)", "kind": "greymend", "need": 2})
		steps.append({"title": "Count the Fog", "desc": "Endure 2 Fog Tally tides (0/2)", "kind": "fogtally", "need": 2})
		steps.append({"title": "Keep Drowned Time", "desc": "Endure 2 Grey Clock tides (0/2)", "kind": "greyclock", "need": 2})
		steps.append({"title": "Ride the Tally", "desc": "Endure 2 Wake Tally tides (0/2)", "kind": "waketally", "need": 2})
		steps.append({"title": "Keep the Long Hour", "desc": "Endure 2 Deep Clock tides (0/2)", "kind": "deepclock", "need": 2})
		steps.append({"title": "Answer the Reckoning", "desc": "Endure 2 Salt Reckon tides (0/2)", "kind": "saltreckon", "need": 2})
		steps.append({"title": "Stand the Count", "desc": "Endure 2 Fog Reckon tides (0/2)", "kind": "fogreckon", "need": 2})
		steps.append({"title": "Close the Audit", "desc": "Endure 2 Grey Reckoning tides (0/2)", "kind": "greyreckon", "need": 2})
		steps.append({"title": "Stand the Session", "desc": "Endure 2 Pale Reckoning tides (0/2)", "kind": "palereckon", "need": 2})
		steps.append({"title": "Fire the Auditor", "desc": "Slay 2 Grey Clerks (0/2)", "kind": "gclerk_kill", "need": 2})
		steps.append({"title": "Refuse Service", "desc": "Slay 2 Salt Bailiffs (0/2)", "kind": "sbailiff_kill", "need": 2})
		steps.append({"title": "Break the Workshop", "desc": "Slay 2 Tithe Wrights (0/2)", "kind": "twright_kill", "need": 2})
		steps.append({"title": "Burn the Receipts", "desc": "Slay 2 Pale Auditors (0/2)", "kind": "pauditor_kill", "need": 2})
		steps.append({"title": "Take Another Seat", "desc": "Slay 2 Deep Ushers (0/2)", "kind": "dusher_kill", "need": 2})
		steps.append({"title": "Refuse the Writ", "desc": "Slay 2 Grey Bailiffs (0/2)", "kind": "gbailiff_kill", "need": 2})
		steps.append({"title": "Cancel the Debt", "desc": "Slay 2 Debt Collectors (0/2)", "kind": "dcollector_kill", "need": 2})
		steps.append({"title": "Audit the Audit", "desc": "Endure 2 Ledger Tides (0/2)", "kind": "ledgertide", "need": 2})
		steps.append({"title": "Ride the Neap", "desc": "Endure 2 Neap Tides (0/2)", "kind": "neaptide", "need": 2})
		steps.append({"title": "End the Procession", "desc": "Silence 3 Deep Vergers (0/3)", "kind": "dverger_kill", "need": 3})
		steps.append({"title": "Rob the Porter", "desc": "Slay 2 Salt Carriers (0/2)", "kind": "scarrier_kill", "need": 2})
		steps.append({"title": "Sworn to the Deep", "desc": "Swear 2 omens (0/2)", "kind": "omen_sworn", "need": 2})
		steps.append({"title": "Hard Bargain", "desc": "Bear 3 omens on one floor (0/1)", "kind": "omen_sworn_floor", "need": 1})
		steps.append({"title": "Purse Sting", "desc": "Survive a pitchwell elite's toll (0/1)", "kind": "affix_pitchwell", "need": 1})
		steps.append({"title": "Silence the Rite", "desc": "Fell 2 salt devouts (0/2)", "kind": "devout_kill", "need": 2})
		steps.append({"title": "Douse the Pitch", "desc": "Slay Pitch Tenders (0/4)", "kind": "pitchtender_kill", "need": 4})
		steps.append({"title": "Banish the Wraith", "desc": "Slay Keel Wraiths (0/4)", "kind": "wraithkill", "need": 4})
		steps.append({"title": "Cut the Rope", "desc": "Slay Salt Gallows (0/3)", "kind": "gallowskill", "need": 3})
		steps.append({"title": "Toll Breaker", "desc": "Silence 8 Soul Tollers (0/8)", "kind": "toll_kill", "need": 8})
		steps.append({"title": "Close the Ledger", "desc": "Slay 6 Keel Scribes (0/6)", "kind": "scribe_kill", "need": 6})
		steps.append({"title": "Cut the Line", "desc": "Slay 5 Salt Widows (0/5)", "kind": "saltwidow_kill", "need": 5})
		steps.append({"title": "Bleed the Leecher", "desc": "Slay 5 Keel Leechers (0/5)", "kind": "leecher_kill", "need": 5})
		steps.append({"title": "Drown the Bell", "desc": "Slay 4 Keel Summoners (0/4)", "kind": "summoner_kill", "need": 4})
		steps.append({"title": "Wring the Leech", "desc": "Slay 5 Rust Leeches (0/5)", "kind": "rustleech_kill", "need": 5})
		steps.append({"title": "Audit the Tither", "desc": "Slay 4 Pale Tithers (0/4)", "kind": "paletither_kill", "need": 4})
		steps.append({"title": "Sea Auditor", "desc": "Make 6 deals in one run (0/6)", "kind": "deal_made", "need": 6})
		steps.append({"title": "Plug the Well", "desc": "Slay PITCHWELL elites (0/3)", "kind": "affix_pitchwell", "need": 3})
		steps.append({"title": "Coin Bleeder", "desc": "Slay GILTBORN elites (0/3)", "kind": "affix_giltborn", "need": 3})
		steps.append({"title": "Cinder Cull", "desc": "Slay CHARBORN elites (0/3)", "kind": "affix_charborn", "need": 3})
		steps.append({"title": "Paid in Full", "desc": "Slay 35 foes with the Gilt Edge (0/35)", "kind": "kill_gilt_edge", "need": 35})
		steps.append({"title": "Lantern Bearer", "desc": "Slay 40 foes with the Lantern Maul (0/40)", "kind": "kill_lantern_maul", "need": 40})
		steps.append({"title": "Hold Your Nose", "desc": "Get bilge-soaked by 2 vents (0/2)", "kind": "bilge_soak", "need": 2})
		steps.append({"title": "Grudge Holder", "desc": "Slay 3 EMBITTERED elites (0/3)", "kind": "affix_embittered", "need": 3})
		steps.append({"title": "Cold Comfort", "desc": "Slay 3 DEATHWARM elites (0/3)", "kind": "affix_deathwarm", "need": 3})
		steps.append({"title": "Turn the Tide", "desc": "Slay 3 TIDEHELD elites (0/3)", "kind": "affix_tideheld", "need": 3})
		steps.append({"title": "To the Marrow", "desc": "Slay 3 MARROWED elites (0/3)", "kind": "affix_marrowed", "need": 3})
		steps.append({"title": "Break the Keel", "desc": "Slay 3 KEELMAW elites (0/3)", "kind": "affix_keelmaw", "need": 3})
		steps.append({"title": "Lose the Gloom", "desc": "Slay 3 GLOOMTOUCHED elites (0/3)", "kind": "affix_gloomtouched", "need": 3})
		steps.append({"title": "Cracked Timber", "desc": "Slay 40 foes with the Hull Render (0/40)", "kind": "kill_hull_render", "need": 40})
		steps.append({"title": "Sing Them Under", "desc": "Slay 40 foes with the Dirge Edge (0/40)", "kind": "kill_dirge_edge", "need": 40})
		steps.append({"title": "Fouling Tide", "desc": "Slay 40 foes with the Barnacle Edge (0/40)", "kind": "kill_barnacle_edge", "need": 40})
		steps.append({"title": "Lantern Call", "desc": "Slay 40 foes with the Wisp Lure (0/40)", "kind": "kill_wisp_lure", "need": 40})
		steps.append({"title": "Anchor's Judgment", "desc": "Slay 40 foes with the Anchor Maul (0/40)", "kind": "kill_anchor_maul", "need": 40})
		steps.append({"title": "The Bell Toll", "desc": "Slay 35 foes with the Wraithbell (0/35)", "kind": "kill_wraithbell", "need": 35})
		steps.append({"title": "Snuffer", "desc": "Slay 4 Wick Tenders (0/4)", "kind": "wick_kill", "need": 4})
		steps.append({"title": "Dry Deck", "desc": "Slay 4 Sodden Deckhands (0/4)", "kind": "deckhand_kill", "need": 4})
		steps.append({"title": "Widowmaker", "desc": "Slay 4 Brine Widows (0/4)", "kind": "widow_kill", "need": 4})
		steps.append({"title": "Break the Hammer", "desc": "Slay 4 Keelwrights (0/4)", "kind": "wright_kill", "need": 4})
		steps.append({"title": "Empty the Ladle", "desc": "Slay 4 Bilge Tenders (0/4)", "kind": "tender_kill", "need": 4})
		steps.append({"title": "Cave-In", "desc": "Slay 4 Keel Sappers (0/4)", "kind": "sapper_kill", "need": 4})
		steps.append({"title": "Cut the Verse", "desc": "Slay 4 Keel Choristers (0/4)", "kind": "chorister_kill", "need": 4})
		steps.append({"title": "Icebreaker", "desc": "Survive a Rime Tide floor (0/1)", "kind": "rimewade", "need": 1})
		steps.append({"title": "Slickwalker", "desc": "Clear an OIL SLICK floor (0/1)", "kind": "slickwalk", "need": 1})
		steps.append({"title": "Ship's Credit", "desc": "Strike 3 deals this run (0/3)", "kind": "deal_made", "need": 3})
		steps.append({"title": "Giant Killer", "desc": "Slay a LEVIATHAN elite (0/1)", "kind": "affix_leviathan", "need": 1})
		steps.append({"title": "Squall Runner", "desc": "Survive a squall floor (0/1)", "kind": "galesurf", "need": 1})
		steps.append({"title": "Glasscutter", "desc": "Slay 3 SUNDERED elites (0/3)", "kind": "affix_sundered", "need": 3})
		steps.append({"title": "Stormbreaker", "desc": "Slay 3 STORMBORN elites (0/3)", "kind": "affix_stormborn", "need": 3})
		steps.append({"title": "Hangman's Walk", "desc": "Clear 2 GALLOWS TIDE floors (0/2)", "kind": "gallowswalk", "need": 2})
		steps.append({"title": "Salt-Fevered", "desc": "Clear 2 SALTSICK floors (0/2)", "kind": "saltwalk", "need": 2})
		steps.append({"title": "Ember Walker", "desc": "Clear 2 EMBER WAKE floors (0/2)", "kind": "emberwalk", "need": 2})
		steps.append({"title": "Storm Salvager", "desc": "Clear 2 RUST STORM floors (0/2)", "kind": "rustwalk", "need": 2})
		steps.append({"title": "Kind Tide", "desc": "Clear 2 BALMY SEA floors (0/2)", "kind": "balmywalk", "need": 2})
		steps.append({"title": "Storm Watcher", "desc": "Clear 2 WAILING WIND floors (0/2)", "kind": "wailwalk", "need": 2})
		steps.append({"title": "Grave Treader", "desc": "Clear 2 SHALLOW GRAVES floors (0/2)", "kind": "gravewalk", "need": 2})
		steps.append({"title": "Powder Rich", "desc": "Clear 2 GUNNER'S LUCK floors (0/2)", "kind": "luckwalk", "need": 2})
		steps.append({"title": "Mooncalf", "desc": "Clear 2 FULL MOON floors (0/2)", "kind": "moonwalk", "need": 2})
		steps.append({"title": "Cold Watched", "desc": "Clear 2 COLD SNAP floors (0/2)", "kind": "snapwalk", "need": 2})
		steps.append({"title": "Weathered", "desc": "Clear 2 SALT FRONT floors (0/2)", "kind": "frontwalk", "need": 2})
		steps.append({"title": "Dregs Drinker", "desc": "Clear 2 FULL DRAUGHT floors (0/2)", "kind": "draughtwalk", "need": 2})
		steps.append({"title": "Strike Breaker", "desc": "Clear 2 BILGE STRIKE floors (0/2)", "kind": "strikewalk", "need": 2})
		steps.append({"title": "Ransom Paid", "desc": "Clear 2 CROWN'S RANSOM floors (0/2)", "kind": "ransomwalk", "need": 2})
		steps.append({"title": "Elite Season", "desc": "Slay 15 crimson elites (0/15)", "kind": "elite_kill", "need": 15})
		steps.append({"title": "Smoke Walker", "desc": "Clear 2 BRINE SMOKE floors (0/2)", "kind": "smokewalk", "need": 2})
		steps.append({"title": "Deck Swab", "desc": "Slay 30 foes in a single descent (0/1)", "kind": "swab30", "need": 1})
		steps.append({"title": "Wright's Toll", "desc": "Slay 8 Foam Wrights (0/8)", "kind": "wright_kill", "need": 8})
		steps.append({"title": "Kennel Duty", "desc": "Slay 10 Keel Mastiffs (0/10)", "kind": "mastiff_kill", "need": 10})
		steps.append({"title": "Moor Cleared", "desc": "Slay 10 Moorlings (0/10)", "kind": "moor_kill", "need": 10})
		steps.append({"title": "Wight's End", "desc": "Slay 8 Deck Wights (0/8)", "kind": "wight_kill", "need": 8})
		steps.append({"title": "Skiff Skein", "desc": "Slay 15 Salt Skiffs (0/15)", "kind": "skiff_kill", "need": 15})
		steps.append({"title": "Lights Out", "desc": "Slay 10 Lantern Jaws (0/10)", "kind": "lamp_kill", "need": 10})
		steps.append({"title": "Ghost Line", "desc": "Slay 8 Keel Ghosts (0/8)", "kind": "keel_kill", "need": 8})
		steps.append({"title": "Cut Down", "desc": "Slay 10 Salt Gibbets (0/10)", "kind": "gibbet_kill", "need": 10})
		steps.append({"title": "Wake Rider", "desc": "Slay 10 foes while swift-footed (0/10)", "kind": "swift_kill", "need": 10})
		steps.append({"title": "Wake Watcher", "desc": "Slay 12 Foamcutters (0/12)", "kind": "foam_kill", "need": 12})
		steps.append({"title": "Unhanged", "desc": "Slay 8 Gallows Revenants (0/8)", "kind": "revenant_kill", "need": 8})
		steps.append({"title": "Fiend Felling", "desc": "Slay 10 Kelter Fiends (0/10)", "kind": "fiend_kill", "need": 10})
		steps.append({"title": "Purse Snatcher", "desc": "Catch 3 Salvage Rats (0/3)", "kind": "rat_catch", "need": 3})
		steps.append({"title": "Lantern Watch", "desc": "Clear 3 PALE LANTERN floors (0/3)", "kind": "lanternwalk", "need": 3})
		steps.append({"title": "Fair Winds", "desc": "Clear 2 LEEWARD floors (0/2)", "kind": "leeward_walk", "need": 2})
		steps.append({"title": "Saltborn", "desc": "Clear 2 SALTGRAVE floors (0/2)", "kind": "saltgrave_walk", "need": 2})
		steps.append({"title": "Bell Silence", "desc": "Slay 4 Bell Ringers (0/4)", "kind": "ringer_kill", "need": 4})
		steps.append({"title": "Lantern Bearer", "desc": "Clear 2 PALE LANTERN floors (0/2)", "kind": "lanternwalk", "need": 2})
		steps.append({"title": "Due Collector", "desc": "Clear 2 WRAITHS' DUE floors (0/2)", "kind": "wraithed", "need": 2})
		steps.append({"title": "Bell Ringer", "desc": "Slay 4 Bell Wardens (0/4)", "kind": "bellwarden_kill", "need": 4})
		steps.append({"title": "Unholy Orders", "desc": "Slay 4 Gutter Chaplains (0/4)", "kind": "chaplain_kill", "need": 4})
		steps.append({"title": "Charged Wrecks", "desc": "Slay 4 CHARGED elites (0/4)", "kind": "affix_charged", "need": 4})
		steps.append({"title": "Unseen Bite", "desc": "Slay 5 foes with Nightfang (0/5)", "kind": "kill_nightfang", "need": 5})
		steps.append({"title": "Night Owl", "desc": "Clear 2 LONG NIGHT floors (0/2)", "kind": "nightwalk", "need": 2})
		steps.append({"title": "Bleeder", "desc": "Slay 4 Salt Leeches (0/4)", "kind": "leech_kill", "need": 4})
		steps.append({"title": "Crow's Wake", "desc": "Clear 2 CROW'S TIDE floors (0/2)", "kind": "crowwalk", "need": 2})
		steps.append({"title": "Sprite Swatter", "desc": "Swat 4 Bilge Sprites (0/4)", "kind": "sprite_kill", "need": 4})
		steps.append({"title": "Iron Droppers", "desc": "Slay 2 KEELMARK elites (0/2)", "kind": "affix_keelmark", "need": 2})
		steps.append({"title": "Salt Walker", "desc": "Clear 2 SALTED DECK floors (0/2)", "kind": "saltwalk", "need": 2})
		steps.append({"title": "First Breach", "desc": "Slay 5 foes with Hullbreaker (0/5)", "kind": "kill_hullbreaker", "need": 5})
		steps.append({"title": "Night Watchman", "desc": "Clear 2 LONG WATCH floors (0/2)", "kind": "watchwalk", "need": 2})
		steps.append({"title": "Wreck Scavenger", "desc": "Clear 2 DRIFT WRECK floors (0/2)", "kind": "wreckwalk2", "need": 2})
		steps.append({"title": "Peal Ringer", "desc": "Slay 5 foes with Chimecleaver (0/5)", "kind": "kill_chimecleaver", "need": 5})
		steps.append({"title": "Bell Silencer", "desc": "Slay 4 Chimeheads (0/4)", "kind": "chime_kill", "need": 4})
		steps.append({"title": "Bargain Sailor", "desc": "Clear 2 GREEDY TIDE floors (0/2)", "kind": "greedywalk", "need": 2})
		steps.append({"title": "Eel Skinner", "desc": "Slay 2 SLIPPERY elites (0/2)", "kind": "affix_slippery", "need": 2})
		steps.append({"title": "Scurvy Cure", "desc": "Slay 5 foes with Scurvy Blade (0/5)", "kind": "kill_scurvy_blade", "need": 5})
		steps.append({"title": "Powder Kegs", "desc": "Clear 2 GUN SMOKE floors (0/2)", "kind": "smokewalk", "need": 2})
		steps.append({"title": "De-Ruster", "desc": "Slay 4 Rust Fanatics (0/4)", "kind": "fanatic_kill", "need": 4})
		steps.append({"title": "Still Waters", "desc": "Clear 2 BLACK CALM floors (0/2)", "kind": "calmwalk", "need": 2})
		steps.append({"title": "Petrel's Wing", "desc": "Slay 5 foes with Storm Petrel (0/5)", "kind": "kill_storm_petrel", "need": 5})
		steps.append({"title": "Oathbreaker", "desc": "Slay an OATHBOUND elite (0/1)", "kind": "affix_oathbound", "need": 1})
		steps.append({"title": "Tithe Dodger", "desc": "Clear 2 KING'S TITHE floors (0/2)", "kind": "tithewalk", "need": 2})
		steps.append({"title": "Brood Breaker", "desc": "Slay 4 Deck Broods (0/4)", "kind": "brood_kill", "need": 4})
		steps.append({"title": "Sawed Off", "desc": "Slay 5 foes with Bilge Saw (0/5)", "kind": "kill_bilge_saw", "need": 5})
		steps.append({"title": "Flushed Out", "desc": "Clear 2 SOUL FLUSH floors (0/2)", "kind": "flushwalk", "need": 2})
		steps.append({"title": "Storm Rider", "desc": "Clear 2 PALE SQUALL floors (0/2)", "kind": "squallwalk", "need": 2})
		steps.append({"title": "Shell Shocked", "desc": "Slay 4 Kelter Husks (0/4)", "kind": "husk_kill", "need": 4})
		steps.append({"title": "Piked It", "desc": "Slay 5 foes with Salt Pike (0/5)", "kind": "kill_salt_pike", "need": 5})
		steps.append({"title": "Unbowed", "desc": "Slay 3 CRUSHING elites (0/3)", "kind": "affix_crushing", "need": 3})
		steps.append({"title": "Bilge Dancer", "desc": "Clear 2 BILGE RUN floors (0/2)", "kind": "bilgewalk", "need": 2})
		steps.append({"title": "Coral Crusher", "desc": "Slay 5 foes with Coral Bludgeon (0/5)", "kind": "kill_coral_bludgeon", "need": 5})
		steps.append({"title": "Pot Hoarder", "desc": "Clear 2 HUNGRY URNS floors (0/2)", "kind": "urnmarch", "need": 2})
		steps.append({"title": "Silence the Choir", "desc": "Slay a Grave Orator (0/1)", "kind": "orator_kill", "need": 1})
	if Stats.floor_num >= 10 and Stats.floor_num % 7 == 3:
		steps.append({"title": "Ghost Hunter", "desc": "Slay an UMBRAL elite (0/1)", "kind": "umbral_kill", "need": 1})
	if Stats.floor_num >= 11 and Stats.floor_num % 6 == 5:
		steps.append({"title": "Pale Fencer", "desc": "Answer two Pale Duelists in kind (0/2)", "kind": "duelist_kill", "need": 2})
	if Stats.floor_num >= 10 and Stats.floor_num % 8 == 4:
		steps.append({"title": "Grave Robber", "desc": "Unlock a Soul Vault", "kind": "vault", "need": 1})
	if Stats.floor_num >= 20 and Stats.floor_num % 6 == 2:
		steps.append({"title": "Deathwalk", "desc": "Blink through the dark twice (0/2)", "kind": "gravestep", "need": 2})
	if Stats.floor_num >= 26 and Stats.floor_num % 4 == 2:
		steps.append({"title": "Spear of Dawn", "desc": "Impale foes with SOUL LANCE", "kind": "lance", "need": 1})
	if Stats.floor_num >= 15 and Stats.floor_num % 9 == 4:
		steps.append({"title": "Wisp Keeper", "desc": "Catch six wandering wisps (0/6)", "kind": "wisp", "need": 6})
	if Stats.floor_num >= 14 and Stats.floor_num % 9 == 5:
		steps.append({"title": "Lucky Soul", "desc": "Gamble at the Gambler's Well (0/1)", "kind": "well", "need": 1})
	if Stats.floor_num >= 9 and Stats.floor_num % 5 == 0:
		steps.append({"title": "Lantern-Blessed", "desc": "Soak 30% HP from a Soul Lantern (0/1)", "kind": "lantern", "need": 1})
	if Stats.floor_num >= 8 and Stats.floor_num % 6 == 1:
		steps.append({"title": "Mapmaker", "desc": "Clear four rooms this floor (0/4)", "kind": "room_clear", "need": 4})
	if Stats.floor_num >= 12 and Stats.floor_num % 7 == 4:
		steps.append({"title": "Deep Pockets", "desc": "Offer the Well three tosses in one visit (0/1)", "kind": "deep_pockets", "need": 1})
	if Stats.floor_num >= 14 and Stats.floor_num % 8 == 6:
		steps.append({"title": "Dethroned", "desc": "Cut down a Crowned paladin (0/2)", "kind": "crowned_kill", "need": 2})
	if Stats.floor_num >= 16 and Stats.floor_num % 12 == 8:
		steps.append({"title": "Thirsting", "desc": "Drink from a Soul Fountain (0/1)", "kind": "fountain", "need": 1})
	if Stats.floor_num >= 12 and Stats.floor_num % 7 == 3:
		steps.append({"title": "Pack Breaker", "desc": "Slay five hounds under the Wolfsbane (0/5)", "kind": "pack_hound", "need": 5})
	if Stats.floor_num >= 15 and Stats.floor_num % 9 == 2:
		steps.append({"title": "Tax Revolt", "desc": "Refuse two Tithings (0/2)", "kind": "tither_kill", "need": 2})
	if Stats.floor_num >= 7 and Stats.floor_num % 6 == 3:
		steps.append({"title": "Wisp Hunt", "desc": "Catch three wandering wisps (0/3)", "kind": "wisp", "need": 3})
	if Stats.floor_num >= 20 and Stats.floor_num % 9 == 4:
		steps.append({"title": "Tide Caller", "desc": "Call the drowned tide once (0/1)", "kind": "tidecall", "need": 1})
	if Stats.floor_num >= 18 and Stats.floor_num % 11 == 7:
		steps.append({"title": "Steel Scrounger", "desc": "Take a blade from a Scavenger's Cache (0/1)", "kind": "cache", "need": 1})
	if Stats.floor_num >= 7 and Stats.floor_num % 7 == 0:
		steps.append({"title": "Bounty Hunter", "desc": "Claim a Bounty Stone contract", "kind": "bounty", "need": 1})
	if Stats.floor_num >= 11 and Stats.floor_num <= 12:
		steps.append({"title": "Vault Thief", "desc": "Claim the Reliquary's gilded hoard (0/1)", "kind": "gilded_chest", "need": 1})
	if Stats.floor_num == 12:
		steps.append({"title": "Sea Prayer", "desc": "Answer a Drowned Altar's offer (0/1)", "kind": "drowned", "need": 1})
		steps.append({"title": "River's Tither", "desc": "Pay the Drowned Altar's River's Tithe (0/1)", "kind": "rivertithe", "need": 1})
		steps.append({"title": "Emissary's Fall", "desc": "Cut down the vault's sworn guard (0/1)", "kind": "emissary_kill", "need": 1})
		steps.append({"title": "Pearl Diver", "desc": "Pry open a Snap Clam while it sleeps (0/1)", "kind": "clam", "need": 1})
		steps.append({"title": "Glasswalker", "desc": "Survive a Glass Sea floor (0/1)", "kind": "glasswalk", "need": 1})
		steps.append({"title": "Keel Breaker", "desc": "Slay 2 soul-snatching Keelhounds (0/2)", "kind": "keelhound_kill", "need": 2})
		steps.append({"title": "Poolside", "desc": "Mend your wounds in a tidepool (0/1)", "kind": "pool", "need": 1})
		steps.append({"title": "Snap Shut", "desc": "Clamp 3 foes with a single Snapjaw (0/1)", "kind": "snapjaw3", "need": 1})
		steps.append({"title": "Lamplighter", "desc": "Bask in a lantern's glow to mend (0/1)", "kind": "lantern", "need": 1})
		steps.append({"title": "Dread Toll", "desc": "Survive a Dread Tide floor (0/1)", "kind": "dreadtide", "need": 1})
		steps.append({"title": "Shellcracker", "desc": "Crack 2 Barnacle Maws (0/2)", "kind": "maw_kill", "need": 2})
		steps.append({"title": "Seaworthy Deal", "desc": "Strike a bargain at a Keelstone (0/1)", "kind": "keelstone", "need": 1})
		steps.append({"title": "Ringing Haul", "desc": "Crack a golden Bell Urn (0/1)", "kind": "bellurn", "need": 1})
		steps.append({"title": "Tidewriter", "desc": "Read a lore stone in the Reliquary (0/1)", "kind": "tidepage", "need": 1})
		steps.append({"title": "Starved Pilgrim", "desc": "Survive a Starved Deep floor (0/1)", "kind": "starved", "need": 1})
		steps.append({"title": "Shark Week", "desc": "Cull 3 Keelhounds on one floor (0/3)", "kind": "keelh3", "need": 1})
		steps.append({"title": "Break the Verse", "desc": "Silence 3 Void Sirens (0/3)", "kind": "siren_kill", "need": 3})
		steps.append({"title": "Choirboy's End", "desc": "Survive a Choir Below floor (0/1)", "kind": "choirfloor", "need": 1})
		steps.append({"title": "Patience Pays", "desc": "Claim a chest under Abyssal Patience (0/1)", "kind": "patient", "need": 1})
		steps.append({"title": "Wax and Wane", "desc": "Seal 5 foes at once with Grave Seal (0/1)", "kind": "seal5", "need": 1})
		steps.append({"title": "Void Dues", "desc": "Crack 2 Void Lanterns (0/2)", "kind": "voidurn", "need": 2})
		steps.append({"title": "Royal Debtor", "desc": "Pay tribute at a Throne's Offering (0/1)", "kind": "throne", "need": 1})
		steps.append({"title": "Pearl Cracker", "desc": "Crack 2 pearlbound shells (0/2)", "kind": "shellcrack", "need": 2})
		steps.append({"title": "Escape Artist", "desc": "Pry loose a Void Pincher (0/1)", "kind": "pinch", "need": 1})
		steps.append({"title": "Moonrise", "desc": "Slay 10 foes with the Moonshell (0/10)", "kind": "moonkill", "need": 10})
		steps.append({"title": "Witching Hour", "desc": "Cast 3 different skills on one floor (0/3)", "kind": "witching", "need": 1})
		steps.append({"title": "Gargoyle's Brood", "desc": "Shatter 5 gargoyles (0/5)", "kind": "garg_kill", "need": 5})
		steps.append({"title": "King's Audit", "desc": "Open 6 chests in one run (0/6)", "kind": "chest_open", "need": 6})
		steps.append({"title": "Shell Shucker", "desc": "Pry open 3 Snap Clams (0/3)", "kind": "clam", "need": 3})
		steps.append({"title": "Undertaker", "desc": "Drag 4+ foes in one Riptide (0/4)", "kind": "riptide4", "need": 1})
		steps.append({"title": "Hymn Breaker", "desc": "Clear a floor while the Abyssal Hymn sounds (0/1)", "kind": "hymnfloor", "need": 1})
		steps.append({"title": "Choir Soloist", "desc": "Slay 5 foes while the Choir Below sings (0/5)", "kind": "choirkill", "need": 5})
		steps.append({"title": "Shell Dancer", "desc": "Pry loose 3 Void Pinchers in one run (0/3)", "kind": "pinch", "need": 3})
		steps.append({"title": "Tide Caller", "desc": "Cast Riptide (0/1)", "kind": "skill_riptide", "need": 1})
		steps.append({"title": "Bone General", "desc": "Raise 3 thralls with the Moonshell (0/3)", "kind": "thrall", "need": 3})
		steps.append({"title": "Siphon Stopper", "desc": "Seal a Soul Siphon while it dozes (0/1)", "kind": "siphon", "need": 1})
		steps.append({"title": "Purse Snatcher", "desc": "Pocket 5 soul vials (0/5)", "kind": "vial", "need": 5})
		steps.append({"title": "Tithe Collector", "desc": "Survive a Soul Siphon's drain (0/1)", "kind": "siphon_hit", "need": 1})
		steps.append({"title": "Keel Commander", "desc": "Keelhaul foes into your blade (0/6)", "kind": "haul", "need": 6})
		steps.append({"title": "Gatekeeper", "desc": "Force open 4 dungeon gates (0/4)", "kind": "gate_open", "need": 4})
		steps.append({"title": "Empty Pockets", "desc": "Get bitten empty-pocketed by a Keelhound (0/1)", "kind": "snatched", "need": 1})
		steps.append({"title": "Widow's Bell", "desc": "Slay 4 foes with the Gravebell (0/4)", "kind": "kill_gravebell", "need": 4})
		steps.append({"title": "Antidote", "desc": "Slay a VENOMED elite (0/1)", "kind": "affix_venomed", "need": 1})
		steps.append({"title": "Wisp Wrangler", "desc": "Catch 6 wandering wisps (0/6)", "kind": "wisp", "need": 6})
		steps.append({"title": "Barnacle Bill", "desc": "Scrape off 3 BARNACLED elites (0/3)", "kind": "affix_barnacled", "need": 3})
		steps.append({"title": "Salvage Boss", "desc": "Slay a TIDAL elite and its flock (0/2)", "kind": "affix_tidal", "need": 2})
		steps.append({"title": "Night Shift", "desc": "Slay 3 foes while an omen floor event runs (0/3)", "kind": "eventkill", "need": 3})
		steps.append({"title": "Short Handed", "desc": "Clear a floor under a SKELETON CREW oath (0/1)", "kind": "crewfloor", "need": 1})
		steps.append({"title": "Scuttlebutt", "desc": "Hear Sir Vane's war stories (0/3)", "kind": "vane_bark", "need": 3})
		steps.append({"title": "Moonbather", "desc": "Drink from a Moonpool shrine (0/1)", "kind": "moonpool", "need": 1})
		steps.append({"title": "Keel Smoked", "desc": "Slay 4 foes with the Tidebrand (0/4)", "kind": "kill_tidebrand", "need": 4})
		steps.append({"title": "Fog Runner", "desc": "Clear a floor under Rolling Fog (0/1)", "kind": "fogfloor", "need": 1})
		steps.append({"title": "Crust Pick", "desc": "Smash 8 urns on one floor (0/8)", "kind": "urn_floor", "need": 1})
		steps.append({"title": "Wet Work", "desc": "Slay 4 tidal-affix elites (0/4)", "kind": "affix_tidal", "need": 4})
		steps.append({"title": "Fat Purse", "desc": "Clear a floor holding 40+ souls", "kind": "fatpurse", "need": 1})
		steps.append({"title": "Fog Seer", "desc": "Discover 10 rooms on one floor (0/10)", "kind": "roomfloor", "need": 1})
		steps.append({"title": "Long Line", "desc": "Slay 6 foes with the Harpoon (0/6)", "kind": "kill_harpoon", "need": 6})
		steps.append({"title": "Veil Render", "desc": "Clear 2 floors while the Thin Veil is drawn (0/2)", "kind": "veilwalk", "need": 2})
		steps.append({"title": "Undertow Dancer", "desc": "Slay 2 RIPTIDE elites without being swept (0/2)", "kind": "affix_riptide", "need": 2})
		steps.append({"title": "Deep Tithe", "desc": "Earn 3 souls back from Soul Tithe kills (0/3)", "kind": "tithe", "need": 3})
		steps.append({"title": "Still Harvest", "desc": "Clear 2 floors in Low Water (0/2)", "kind": "lowwalk", "need": 2})
		steps.append({"title": "Net Mender", "desc": "Slay 6 foes with the Driftnet (0/6)", "kind": "kill_driftnet", "need": 6})
		steps.append({"title": "Deep Drink", "desc": "Clear 2 floors sworn to DARK WATER (0/2)", "kind": "darkwalk", "need": 2})
		steps.append({"title": "Rat Catcher", "desc": "Slay 5 Mirelings before they chill you (0/5)", "kind": "mireling_kill", "need": 5})
		steps.append({"title": "Salt Scraper", "desc": "Strip the hoard from 2 BRINEBOUND elites (0/2)", "kind": "affix_brinebound", "need": 2})
		steps.append({"title": "Arms Inspector", "desc": "Take 2 deals at a Quartermaster's Post (0/2)", "kind": "qm", "need": 2})
		steps.append({"title": "Hooked Butcher", "desc": "Slay 6 foes with the Guthook (0/6)", "kind": "kill_guthook", "need": 6})
		steps.append({"title": "Salt on the Wind", "desc": "Fell 4 Saltghasts (0/4)", "kind": "saltghast_kill", "need": 4})
		steps.append({"title": "Pack Breaker", "desc": "Fell 2 FERAL elites (0/2)", "kind": "affix_feral", "need": 2})
		steps.append({"title": "Choir Member", "desc": "Take 2 deals at a Siren's Conch (0/2)", "kind": "siren", "need": 2})
		steps.append({"title": "Deep Drifter", "desc": "Clear 2 floors under a DRIFT TIDE (0/2)", "kind": "driftwalk", "need": 2})
		steps.append({"title": "Full Hammer", "desc": "Forge your blade 3 times (0/3)", "kind": "forge", "need": 3})
		steps.append({"title": "Conch Holder", "desc": "End 2 floors holding 40+ souls (0/2)", "kind": "fatpurse", "need": 2})
		steps.append({"title": "Pot Shard", "desc": "Smash 6 urns (0/6)", "kind": "urnsmash", "need": 6})
		steps.append({"title": "Hull Cracker", "desc": "Slay 6 foes with the Whelk Maul (0/6)", "kind": "kill_whelk_maul", "need": 6})
		steps.append({"title": "Steady Arm", "desc": "Fell 4 Wavers (0/4)", "kind": "waver_kill", "need": 4})
		steps.append({"title": "Pickpocket's Justice", "desc": "Fell 2 MISER elites (0/2)", "kind": "affix_miser", "need": 2})
		steps.append({"title": "Purse Watcher", "desc": "Lose 4 souls to misers and keep swinging (0/4)", "kind": "miser_loss", "need": 4})
		steps.append({"title": "Many Blades", "desc": "Swap between owned weapons 6 times (0/6)", "kind": "swap", "need": 6})
		steps.append({"title": "Drag Line", "desc": "Drag in 6 kills with the Bone Scourge (0/6)", "kind": "kill_scourge", "need": 6})
		steps.append({"title": "Swarm Shepherd", "desc": "Walk 2 SOUL SWARM floors to the end (0/2)", "kind": "swarmwalk", "need": 2})
		steps.append({"title": "Rust Scrap", "desc": "Fell 2 TIDEWORN elites (0/2)", "kind": "affix_tideworn", "need": 2})
		steps.append({"title": "Anchor Watch", "desc": "Moor 6 kills with the Chain Anchor (0/6)", "kind": "kill_chain_anchor", "need": 6})
		steps.append({"title": "Blood Price", "desc": "Pay the Soulfall twice (0/2)", "kind": "skill_soulfall", "need": 2})
		steps.append({"title": "Beak Clipped", "desc": "Fell 4 Keelbeaks (0/4)", "kind": "keelbeak_kill", "need": 4})
		steps.append({"title": "Dulled Edge", "desc": "Shear 6 kills with the Tide Shear (0/6)", "kind": "kill_tide_shear", "need": 6})
		steps.append({"title": "Proven", "desc": "Walk 2 GAUNTLET floors to the end (0/2)", "kind": "gauntletwalk", "need": 2})
		steps.append({"title": "Unload", "desc": "Slay 4 Deck Gunners (0/4)", "kind": "gunner_kill", "need": 4})
		steps.append({"title": "Gnawed Down", "desc": "Slay 6 Chum Gnawers (0/6)", "kind": "gnawer_kill", "need": 6})
		steps.append({"title": "Dead Air", "desc": "Slay 4 Reef Callers (0/4)", "kind": "caller_kill", "need": 4})
		steps.append({"title": "Douse the Light", "desc": "Slay 4 Lantern Jacks (0/4)", "kind": "jack_kill", "need": 4})
		steps.append({"title": "Widow's Web", "desc": "Slay 4 Hull Widows (0/4)", "kind": "widow_kill", "need": 4})
		steps.append({"title": "Herald Silenced", "desc": "Slay 4 Salt Heralds (0/4)", "kind": "herald_kill", "need": 4})
		steps.append({"title": "Water-Bearer", "desc": "Slay 2 PARCHED elites (0/2)", "kind": "affix_parched", "need": 2})
		steps.append({"title": "Dry Land", "desc": "Slay 2 DROWNING elites (0/2)", "kind": "affix_drowning", "need": 2})
		steps.append({"title": "Doom Silencer", "desc": "Slay 2 DOOMSAYER elites (0/2)", "kind": "affix_doomsayer", "need": 2})
		steps.append({"title": "Grim Harvest", "desc": "Slay 2 GRIM elites (0/2)", "kind": "affix_grim", "need": 2})
		steps.append({"title": "Web Cutter", "desc": "Slay 2 WEBBED elites (0/2)", "kind": "affix_webbed", "need": 2})
		steps.append({"title": "Salt Cut", "desc": "Slay 2 SALTED elites (0/2)", "kind": "affix_salted", "need": 2})
		steps.append({"title": "Rust Budget", "desc": "Slay 2 CORRODED elites (0/2)", "kind": "affix_corroded", "need": 2})
		steps.append({"title": "Anchor Raised", "desc": "Fell 2 KEELBOUND elites (0/2)", "kind": "affix_keelbound", "need": 2})
		steps.append({"title": "Salt Rich", "desc": "Walk off a floor holding 60+ souls (0/2)", "kind": "soulrich", "need": 2})
		steps.append({"title": "Reckoner", "desc": "Cast Dead Reckoning 3 times (0/3)", "kind": "skill_deadreckon", "need": 3})
		steps.append({"title": "Deck Walker", "desc": "Cast Sea Legs 3 times (0/3)", "kind": "skill_sealegs", "need": 3})
		steps.append({"title": "Silence the Choir", "desc": "Slay 3 Salt Cantors (0/3)", "kind": "cantor_kill", "need": 3})
		steps.append({"title": "Bargain Hunter", "desc": "Clear 2 MERCHANT TIDE floors (0/2)", "kind": "martwalk", "need": 2})
		steps.append({"title": "Unwracked", "desc": "Slay 3 WRACK elites (0/3)", "kind": "affix_wrack", "need": 3})
		steps.append({"title": "Widow's Wake", "desc": "Slay 3 Rotting Brides (0/3)", "kind": "bride_kill", "need": 3})
		steps.append({"title": "Swept Clean", "desc": "Slay 5 foes with Quarterstaff (0/5)", "kind": "kill_quarterstaff", "need": 5})
		steps.append({"title": "Sang Along", "desc": "Slay 5 foes with Reef Chorus (0/5)", "kind": "kill_reef_chorus", "need": 5})
		steps.append({"title": "Skewered", "desc": "Slay 5 foes with Harpooner (0/5)", "kind": "kill_harpooner", "need": 5})
		steps.append({"title": "Gaffed It", "desc": "Slay 5 foes with Gaff Hook (0/5)", "kind": "kill_gaff_hook", "need": 5})
		steps.append({"title": "Rip Current", "desc": "Slay 5 foes with Riptide Fang (0/5)", "kind": "kill_riptide_fang", "need": 5})
		steps.append({"title": "Hook, Line, Sinker", "desc": "Slay 5 foes with Captain's Hook (0/5)", "kind": "kill_captains_hook", "need": 5})
		steps.append({"title": "Murk Runner", "desc": "Slay 6 foes with Murkmaker (0/6)", "kind": "kill_murkmaker", "need": 6})
		steps.append({"title": "Powder Burn", "desc": "Slay 6 foes with Saltpeter (0/6)", "kind": "kill_saltpeter", "need": 6})
		steps.append({"title": "Warm Blooded", "desc": "Wear off 8 chills (Warm Blood relic) (0/8)", "kind": "chillshake", "need": 8, "relic": "warm_blood"})
		steps.append({"title": "Silk Draw", "desc": "Slay 6 foes with Silkfang (0/6)", "kind": "kill_silkfang", "need": 6})
		steps.append({"title": "Brine Edge", "desc": "Slay 6 foes with the Brine Cutlass (0/6)", "kind": "kill_brine_cutlass", "need": 6})
		steps.append({"title": "Hook Line", "desc": "Slay 6 foes with the Bilge Hook (0/6)", "kind": "kill_bilge_hook", "need": 6})
		steps.append({"title": "Bloodtide Ritual", "desc": "Cast Bloodtide (Lv47) (0/1)", "kind": "skill_bloodtide", "need": 1})
		steps.append({"title": "Keelwright", "desc": "Split the keel 2 times (0/2)", "kind": "skill_keelsplit", "need": 2})
		steps.append({"title": "Flat Side", "desc": "Slay 6 foes with the Oarblade (0/6)", "kind": "kill_oarblade", "need": 6})
		steps.append({"title": "Sawbones", "desc": "Saw 6 kills with the Whalebone Saw (0/6)", "kind": "kill_whale_saw", "need": 6})
		steps.append({"title": "Witch Hunter", "desc": "Fell 4 Bilge Witches (0/4)", "kind": "witch_kill", "need": 4})
		steps.append({"title": "Rust Scrub", "desc": "Slay 4 Rust Jaws (0/4)", "kind": "rustjaw_kill", "need": 4})
		steps.append({"title": "Fasting", "desc": "Clear 2 floors without taking a shrine's deal (0/2)", "kind": "fasting", "need": 2})
		steps.append({"title": "Quickstep", "desc": "Walk 2 BRISK TIDE floors to the end (0/2)", "kind": "briskwalk", "need": 2})
		steps.append({"title": "Keel Sworn", "desc": "Take 4 Keelstone deals across a run (0/4)", "kind": "keelstone", "need": 4})
		steps.append({"title": "Stone Signed", "desc": "Take 2 Keelstone deals (0/2)", "kind": "keelstone", "need": 2})
		steps.append({"title": "Grave Fed", "desc": "Take 3 Mahzan deals (0/3)", "kind": "mahzan", "need": 3})
		steps.append({"title": "Wreckwalker", "desc": "Clear 2 HALFWRECK floors (0/2)", "kind": "wreckwalk", "need": 2})
		steps.append({"title": "Night Warden", "desc": "Clear 2 DARK LANTERN floors (0/2)", "kind": "lampwalk", "need": 2})
		steps.append({"title": "Hollow Walker", "desc": "Clear 2 MIRE HOLLOW floors (0/2)", "kind": "mirewalk", "need": 2})
		steps.append({"title": "Bile Swallower", "desc": "Clear 2 BILE TIDE floors (0/2)", "kind": "bilewalk", "need": 2})
		steps.append({"title": "Sodden Feet", "desc": "Clear 2 SODDEN HALLS floors (0/2)", "kind": "soddenwalk", "need": 2})
		steps.append({"title": "Barnacle Breaker", "desc": "Clear 2 BARNACLE BLOOM floors (0/2)", "kind": "bloomwalk", "need": 2})
		steps.append({"title": "Kelp Walker", "desc": "Clear 2 KELP BED floors (0/2)", "kind": "kelpwalk", "need": 2})
		steps.append({"title": "Swell Rider", "desc": "Clear 2 SWELL TIDE floors (0/2)", "kind": "swellwalk", "need": 2})
		steps.append({"title": "White Cap Runner", "desc": "Cross 2 floors under HIGH SEAS (0/2)", "kind": "highseawalk", "need": 2})
		steps.append({"title": "Eel Runner", "desc": "Clear 2 floors under an EEL TIDE (0/2)", "kind": "eelwalk", "need": 2})
		steps.append({"title": "Mercy Walker", "desc": "Clear 2 floors under a MERCY TIDE (0/2)", "kind": "mercywalk", "need": 2})
		steps.append({"title": "Gale Runner", "desc": "Walk 2 GALE TIDE floors to the end (0/2)", "kind": "galewalk", "need": 2})
		steps.append({"title": "Wreck Picker", "desc": "Walk 2 SALVAGE TIDE floors to the end (0/2)", "kind": "salvagewalk", "need": 2})
		steps.append({"title": "Shoal Runner", "desc": "Walk 2 SHOAL TIDE floors to the end (0/2)", "kind": "shoalwalk", "need": 2})
	if Stats.floor_num == 11:
		steps.append({"title": "Soul Fisher", "desc": "Net three drifting wisps (0/3)", "kind": "wisp", "need": 3})
	if Stats.floor_num >= 13 and Stats.floor_num % 8 == 5:
		steps.append({"title": "Ten-Soul Net", "desc": "Bless yourself with the Lucky Net (0/1)", "kind": "lucky_net", "need": 1})
	if Stats.floor_num >= 9 and Stats.floor_num % 6 == 3:
		steps.append({"title": "Shieldbreaker", "desc": "Slay Shieldbearers (0/3)", "kind": "shield_kill", "need": 3})
	if Stats.floor_num >= 5 and Stats.floor_num % 5 == 1:
		steps.append({"title": "Forge-Fed", "desc": "Forge your blade at a Soul Forge", "kind": "forge", "need": 1})
		steps.append({"title": "Floor Sweep", "desc": "Clear %d rooms of skeletons" % room_count, "kind": "clear_floor", "need": room_count})
		steps.append({"title": "Treasure Chest", "desc": "Find & open the chest in the final room", "kind": "open_chest", "need": 1})
		steps.append({"title": "Descend", "desc": "Tap to descend to the next floor", "kind": "descend", "need": 1})
	for i in range(steps.size()):
		steps[i]["num"] = i + 1
		steps[i]["total"] = steps.size()
	return steps
