class_name SkillsDb
# Database skill aktif. Terbuka berdasarkan level run. Cooldown per skill.

const DB := {
	"dash": {
		"name": "Shadow Rush", "short": "DASH", "cd": 5.0, "unlock": 1,
		"desc": "Dash forward, briefly invincible.",
	},
	"whirl": {
		"name": "Whirlwind", "short": "SPIN", "cd": 9.0, "unlock": 3,
		"desc": "360° slash: 2x ATK to all nearby enemies.",
	},
	"thunder": {
		"name": "Vengeful Thunder", "short": "BOLT", "cd": 14.0, "unlock": 5,
		"desc": "Lightning strikes the 3 nearest enemies: 3x ATK + stun.",
	},
	"warcry": {
		"name": "War Cry", "short": "CRY", "cd": 18.0, "unlock": 7,
		"desc": "Roar that knocks enemies back and grants +50% ATK for 5s.",
	},
	"nova": {
		"name": "Soul Nova", "short": "NOVA", "cd": 20.0, "unlock": 9,
		"desc": "Soul blast: 2x ATK to all foes nearby — each kill mends 1 HP.",
	},
	"judge": {
		"name": "Heaven's Judgment", "short": "JUDGE", "cd": 12.0, "unlock": 11,
		"desc": "Smite the nearest foe: 3x ATK — up to 5x against the wounded. A kill pays 2 souls.",
	},
	"sunder": {
		"name": "Sundering Blow", "short": "SNDR", "cd": 13.0, "unlock": 13,
		"desc": "Guard-shattering strike: 2.5x ATK — the foe takes +30% damage for 4s.",
	},
	"chains": {
		"name": "Grave Chains", "short": "CHN", "cd": 16.0, "unlock": 15,
		"desc": "Spectral chains bind all nearby foes for 2.2s + 0.8x ATK.",
	},
	"storm": {
		"name": "Soul Storm", "short": "STORM", "cd": 28.0, "unlock": 17,
		"desc": "Call the deep's fury: lightning smites EVERY awake foe for 1.5x ATK.",
	},
	"mend": {
		"name": "Oracle's Mend", "short": "MEND", "cd": 40.0, "unlock": 19,
		"desc": "Her thread closes wounds: restore 2 HP and shake off chill and chains.",
	},
	"seismic": {"name": "Seismic Slam", "short": "SEIS", "cd": 30.0, "unlock": 23, "desc": "Slam the dungeon floor — nearby foes take 1.8x ATK and are stunned."},
	"kingsfall": {"name": "Kingsfall", "short": "KING", "cd": 45.0, "unlock": 25, "desc": "Bring down the crown — 3x ATK to all awake foes; bosses take half again."},
	"lance": {"name": "Soul Lance", "short": "LANCE", "cd": 22.0, "unlock": 27, "desc": "A piercing line of soul-light — 1.4x ATK through every foe in your facing lane."},
	"gravestep": {"name": "Gravestep", "short": "STEP", "cd": 16.0, "unlock": 29, "desc": "Blink through the dark — 1.2x ATK burst on arrival."},
	"tidecall": {"name": "Tide Call", "short": "TCAL", "cd": 20.0, "unlock": 31, "desc": "Summon the drowned tide — 1.5x ATK, hurls foes back and slows them."},
	"snapjaw": {"name": "Snapjaw", "short": "SNAP", "cd": 18.0, "unlock": 33, "desc": "A spectral clam erupts — foes nearby are clamped shut for 1.5s and bitten for 1.2x ATK."},
	"graveseal": {"name": "Grave Seal", "short": "SEAL", "cd": 22.0, "unlock": 35, "desc": "A wax seal of the King himself — every foe in the room is sealed still for 2.5s."},
	"riptide": {"name": "Riptide", "short": "TIDE", "cd": 24.0, "unlock": 37, "desc": "The floor turns to black water — every foe within 3 tiles is dragged to your feet, soaked and slowed."},
	"soultithe": {"name": "Soul Tithe", "short": "TITHE", "cd": 26.0, "unlock": 39, "desc": "Offer 3 souls to smite every awake foe for 2x ATK — the kill refunds its share."},
	"soulfall": {"name": "Soulfall", "short": "FALL", "cd": 30.0, "unlock": 43, "desc": "Spend 15% of your current HP — foes within 2.2 tiles take double what you paid."},
	"bloodtide": {"name": "Bloodtide", "short": "BTID", "cd": 16.0, "unlock": 47, "desc": "For 5 seconds every kill pays +1 soul."},
	"sealegs": {"name": "Sea Legs", "short": "LEGS", "cd": 14.0, "unlock": 49, "desc": "Find your sea legs — shed every hex, chill and root; +15% speed for 2.5s."},
	"deadreckon": {"name": "Dead Reckoning", "short": "RECK", "cd": 20.0, "unlock": 51, "desc": "Chart every foe in the room — they take +25% damage for 6s."},
	"becalm": {"name": "Becalm", "short": "CALM", "cd": 18.0, "unlock": 53, "desc": "The sea goes still — every foe in the room drags at half speed for 6s."},
	"irontide": {"name": "Iron Tide", "short": "IRON", "cd": 24.0, "unlock": 55, "desc": "Skin turns to hull-plating — for 5s, every blow against you bites its striker back for half."},
	"riptidesnare": {"name": "Riptide Snare", "short": "SNARE", "cd": 13.0, "unlock": 77, "desc": "A rip current knots beneath you — foes near you are rooted where they stand."},
	"saltward": {"name": "Salt Ward", "short": "WARD", "cd": 12.0, "unlock": 79, "desc": "A ring of burning salt — foes near you wade half-speed for a breath."},
	"kingstoll": {"name": "King's Toll", "short": "KTOL", "cd": 24.0, "unlock": 99, "desc": "Ring the throne's bell — every foe within 4 tiles takes 2.5× ATK and is thrown back."},
	"brinevolley": {"name": "Brine Volley", "short": "VOLLEY", "cd": 13.0, "unlock": 107, "desc": "Call down the grey rain — the 3 nearest foes take 1.1× ATK and are slowed 2s."},
	"choruscall": {"name": "Chorus Call", "short": "CHO", "cd": 18.0, "unlock": 115, "desc": "Sing the sunken verse — every foe slowed 40% for 5s."},
	"deckwash": {"name": "Deckwash", "short": "DEW", "cd": 20.0, "unlock": 117, "desc": "Send the sea down the deck — every foe thrown back and reeling."},
	"hullkneel": {"name": "Hull Kneel", "short": "KNL", "cd": 22.0, "unlock": 119, "desc": "The deck itself bows — every foe is slowed for 6s."},
	"crowsnest": {"name": "Crow's Nest", "short": "NEST", "cd": 24.0, "unlock": 123, "desc": "The lookout calls — every foe is marked: +25% damage taken for 5s."},
	"stormflag": {"name": "Storm Flag", "short": "FLAG", "cd": 22.0, "unlock": 127, "desc": "Raise the fallen standard — +50% ATK for 4s and every foe is slowed."},
	"shellup": {"name": "Barnacle Shell", "short": "SHELL", "cd": 20.0, "unlock": 131, "desc": "Grow a crust of old armor — +6 ARMOR for 6s."},
	"bilgesurge": {"name": "Bilge Surge", "short": "SURGE", "cd": 16.0, "unlock": 135, "desc": "The hold's black water rises at your command — nearby foes are thrown and struck for 70% ATK."},
	"severline": {"name": "Sever Line", "short": "SEVER", "cd": 14.0, "unlock": 139, "desc": "Throw the line wide — the farthest foe is hauled to your blade and slowed."},
	"secondwind": {"name": "Second Wind", "short": "WIND", "cd": 30.0, "unlock": 143, "desc": "Catch your breath mid-fight — recover 18% of your missing health."},
	"galewind": {"name": "Galewind", "short": "GWND", "cd": 16.0, "unlock": 147, "desc": "Throw your shoulder to the squall — foes before you are blown back and slowed."},
	"keelhurl": {"name": "Keelhurl", "short": "HURL", "cd": 12.0, "unlock": 151, "desc": "Heave a spectral anchor at the nearest foe — heavy blow, stunned 2s."},
	"maelstrom": {"name": "Maelstrom", "short": "MAEL", "cd": 20.0, "unlock": 155, "desc": "Open a whirlpool at your feet — foes within 4 tiles are dragged in and slowed 3s."},
	"deckflare": {"name": "Deck Flare", "short": "FLARE", "cd": 18.0, "unlock": 159, "desc": "Strike the deck lantern — your blade burns +50% ATK for 6s."},
	"wickdraw": {"name": "Wickdraw", "short": "WICK", "cd": 22.0, "unlock": 163, "desc": "Draw their fire out — foes within 5 tiles slow 4s and bleed open (+30% damage taken, 3s)."},
	"sirenscall": {"name": "Siren's Call", "short": "CALL", "cd": 18.0, "unlock": 165, "desc": "Sing the pull — foes within 2.2 tiles are dragged in and slowed 4s (0.8× ATK graze)."},
	"bloodmark": {"name": "Bloodmark", "short": "BMARK", "cd": 16.0, "unlock": 167, "desc": "Mark the 3 nearest foes — they bleed wide, taking +25% damage for 5s."},
	"deadeye": {"name": "Deadeye", "short": "EYE", "cd": 14.0, "unlock": 169, "desc": "Steady your eye — +25% crit chance for 5s."},
	"rigger": {"name": "Rigger's Prayer", "short": "RIG", "cd": 16.0, "unlock": 171, "desc": "A prayer for quick line — +22% speed, +12% attack speed for 5s."},
	"saltskin": {"name": "Saltskin", "short": "SALT", "cd": 18.0, "unlock": 175, "desc": "Cake your hide in sea-salt — +15% dodge, +2 armor for 6s."},
	"ironwake": {"name": "Ironwake", "short": "IRKW", "cd": 16.0, "unlock": 177, "desc": "Plow through the swell like a prow — +2 armor, +10% speed for 5s."},
	"brineward": {"name": "Brineward", "short": "BRIN", "cd": 15.0, "unlock": 179, "desc": "A wall of brine — +4 armor, +10% dodge for 4s."},
	"wakeveil": {"name": "Wakeveil", "short": "VEIL", "cd": 14.0, "unlock": 183, "desc": "Ride your own wake half-seen — +12% dodge, +6% speed for 5s."},
	"keelbolt": {"name": "Keelbolt", "short": "KBLT", "cd": 10.0, "unlock": 187, "desc": "Fire the keel-harpoon — the nearest foe takes 3.5× ATK and is stunned 1s."},
	"galepulse": {"name": "Gale Pulse", "short": "GALE", "cd": 12.0, "unlock": 191, "desc": "A burst of storm-air — every foe in reach is hurled back and takes 1.5× ATK."},
	"keelover": {"name": "Keel Over", "short": "OVER", "cd": 13.0, "unlock": 195, "desc": "Drop the keel-anchor — nearby foes are dragged to you and staggered."},
	"sounddeep": {"name": "Sound the Deep", "short": "DEEP", "cd": 14.0, "unlock": 199, "desc": "A toll from below — nearby foes take 1.5x ATK, are hurled back and staggered."},
	"saltpall": {"name": "Salt Pall", "short": "PALL", "cd": 13.0, "unlock": 203, "desc": "A grey pall falls — nearby foes take 1.2x ATK and drag their feet for 3s."},
	"keelhaul": {"name": "Keelhaul", "short": "HAUL", "cd": 12.0, "unlock": 207, "desc": "Harpoon the nearest foe and drag it under your keel — pulled to melee and stunned 1.4s."},
	"belltoll": {"name": "Bell Toll", "short": "TOLL", "cd": 15.0, "unlock": 211, "desc": "Ring the deep bell — foes in 5.5 tiles take 1.4x ATK and stagger toward the sound."},
	"dredge": {"name": "Dredge", "short": "DREG", "cd": 14.0, "unlock": 215, "desc": "Drag the nearest foe's purse — it takes 1.8x ATK and pays you 2 souls."},
	"grimpress": {"name": "Grim Press", "short": "PRESS", "cd": 16.0, "unlock": 219, "desc": "A wake-crushing blow — foes in 4 tiles take 2.0x ATK and slow for 2s."},
	"palemark": {"name": "Pale Mark", "short": "MARK", "cd": 12.0, "unlock": 223, "desc": "Sight the strongest foe's pale line — it takes +25% damage for 6s."},
	"greywake": {"name": "Grey Wake", "short": "GWAKE", "cd": 15.0, "unlock": 227, "desc": "Drag the sea's grey tail across the deck — all foes within 5 tiles are slowed 3s and take 1.2x ATK."},
	"crestwake": {"name": "Crestwake", "short": "CREST", "cd": 17.0, "unlock": 231, "desc": "Ride the crest — foes within 5 tiles are slowed 2.5s while the swell lifts you +8% speed this run."},
	"wakecut": {"name": "Wake Cut", "short": "WCUT", "cd": 10.0, "unlock": 233, "desc": "A forward wake-shear — foes in a 4-tile cone ahead take 1.6x ATK and are thrown back."},
	"keelring": {"name": "Keel Ring", "short": "KRING", "cd": 14.0, "unlock": 235, "desc": "The keel bell tolls outward — foes within 4 tiles take 0.9x ATK and are stunned 1.2s."},
	"fogcall": {"name": "Fog Call", "short": "FCALL", "cd": 16.0, "unlock": 237, "desc": "You sing the fog in — foes within 4.5 tiles take 0.8x ATK and are drawn to your side."},
	"sanctum": {"name": "Salt Sanctum", "short": "SNCTM", "cd": 18.0, "unlock": 239, "desc": "A ring of brined ground — mend 12% max HP and drive every foe within 3 tiles back."},
	"saltmantle": {"name": "Salt Mantle", "short": "MNTL", "cd": 20.0, "unlock": 241, "desc": "The sea throws its mantle over you — foes within 3 tiles are staggered 0.6s as the brine shocks through."},
	"fathomward": {"name": "Fathom Ward", "short": "FWRD", "cd": 16.0, "unlock": 243, "desc": "A ward of deep water bursts outward — 1.1x damage to foes within 2.5 tiles and shoves them back."},
	"saltcrest": {"name": "Salt Crest", "short": "CRST", "cd": 14.0, "unlock": 245, "desc": "A crest of brine rolls out — 0.8x damage to foes within 3.5 tiles and slows them 1.5s."},
	"greyreprieve": {"name": "Grey Reprieve", "short": "RPRV", "cd": 24.0, "unlock": 247, "desc": "The pale court grants a stay — purge every ailment and mend 8% max HP."},
	"deeppeal": {"name": "Deep Peal", "short": "PEAL", "cd": 18.0, "unlock": 249, "desc": "Strike the deep bell — 0.9x damage to foes within 2 tiles and stuns them 1.5s."},
	"whitewake": {"name": "White Wake", "short": "WWAK", "cd": 26.0, "unlock": 257, "desc": "The white wake crashes — 0.9x damage to foes within 4 tiles and hurls them back."},
	"trenchtoll": {"name": "Trench Toll", "short": "TTOL", "cd": 28.0, "unlock": 259, "desc": "The trench collects its due — 0.8x damage and a 2s slow to foes within 4.5 tiles; each struck foe pays +1 soul."},
	"sessioncall": {"name": "Session Call", "short": "SCAL", "cd": 30.0, "unlock": 261, "desc": "The court's session bell rings — foes within 5 tiles are hauled to you and staggered 0.8s."},
	"edictcall": {"name": "Edict Call", "short": "ECAL", "cd": 32.0, "unlock": 263, "desc": "The court's ruling falls — 1.2x damage to all foes within 4 tiles; the ruling taxes each struck foe +1 soul."},
	"fealtycall": {"name": "Fealty Call", "short": "FCAL", "cd": 34.0, "unlock": 265, "desc": "The court's fealty bell tolls — foes within 5.5 tiles are hauled to you and take 0.6x damage; each sworn foe pays +1 soul."},
	"neapcall": {"name": "Neap Call", "short": "NEAP", "cd": 30.0, "unlock": 267, "desc": "Call the slack tide up through the floor — every foe on the floor is slowed 50% for 6s."},
	"springcall": {"name": "Spring Call", "short": "SPRING", "cd": 32.0, "unlock": 269, "desc": "Call the spring tide in — foes within 6 tiles are dragged to your blade, take 0.7x ATK, and pay +1 soul each."},
	"whiteknell": {"name": "White Knell", "short": "WKNE", "cd": 24.0, "unlock": 255, "desc": "Toll the white bell — 0.75x damage to foes within 3.5 tiles; each struck foe is audited for +1 soul."},
	"greytoll": {"name": "Grey Toll", "short": "GTOL", "cd": 22.0, "unlock": 253, "desc": "Ring the reckoning's bell — 0.8x damage to foes within 3 tiles, and the count yields +1 soul per foe struck."},
	"palewake": {"name": "Pale Wake", "short": "PWAK", "cd": 20.0, "unlock": 251, "desc": "Your wake turns grey and heavy — 0.7x damage to foes within 3.5 tiles and slows them 2s."},
	"saltwake": {"name": "Salt Wake", "short": "WAKE", "cd": 14.0, "unlock": 111, "desc": "Cut the water behind you — a freezing wake stuns the 3 nearest foes 1.2s, then slows them."},
	"netcast": {"name": "Net Cast", "short": "CAST", "cd": 12.0, "unlock": 105, "desc": "Throw the purse-net wide — foes within reach are rooted 3s."},
	"chumtoss": {"name": "Chum Toss", "short": "CHUM", "cd": 11.0, "unlock": 101, "desc": "Lob a chum line ahead — foes in the lane take 1.2× ATK and are slowed 2s."},
	"tidesnatch": {"name": "Tide Snatch", "short": "SNATCH", "cd": 14.0, "unlock": 97, "desc": "A hand from the undertow — the 3 nearest foes are dragged to you and dragged slow 3s."},
	"deathknell": {"name": "Death Knell", "short": "KNELL", "cd": 20.0, "unlock": 95, "desc": "Toll for the fallen — foes within 3 tiles take 1.0× ATK and freeze 2.5s."},
	"deckrupture": {"name": "Deck Rupture", "short": "RUPT", "cd": 18.0, "unlock": 93, "desc": "Stamp the planks to splinters — foes within 2 tiles take 2.0× ATK and reel 1.5s."},
	"keelsplitter": {"name": "Keel Splitter", "short": "KSPLIT", "cd": 16.0, "unlock": 91, "desc": "Bring the prow down on one skull — the nearest foe takes 3.0× ATK."},
	"saltmaw": {"name": "Salt Maw", "short": "MAW", "cd": 15.0, "unlock": 89, "desc": "The deep bites — every foe within two tiles takes 1.4× ATK and wades slow for 2s."},
	"ghostnet": {"name": "Ghost Net", "short": "NET", "cd": 13.0, "unlock": 87, "desc": "Cast the drowned fisher's net — every foe near you wades half-speed for 4s."},
	"brinelash": {"name": "Brine Lash", "short": "LASH", "cd": 10.0, "unlock": 85, "desc": "Crack a rope of brine — the three nearest foes take 1.2× ATK and reel."},
	"warpaint": {"name": "Warpaint", "short": "PAINT", "cd": 14.0, "unlock": 83, "desc": "Slap the old war-ochre on — +30% ATK for 5s."},
	"bilgesnare": {"name": "Bilge Snare", "short": "SNARE2", "cd": 11.0, "unlock": 81, "desc": "A knot of bilge under the nearest foe — it roots fast and drinks deep."},
	"salvagehook": {"name": "Salvage Hook", "short": "HOOK", "cd": 11.0, "unlock": 75, "desc": "Fling the boarding hook — the nearest foe is dragged to your blade and stunned."},
	"crowsdive": {"name": "Crow's Dive", "short": "DIVE", "cd": 9.0, "unlock": 73, "desc": "Spring into the rigging and drop — landing stuns foes near you and quickens your next strikes."},
	"hullsplinter": {"name": "Hullsplinter", "short": "SPLNT", "cd": 15.0, "unlock": 71, "desc": "Crack the deck — shrapnel flies in a ring around you, wounding every foe in reach."},
	"keelram": {"name": "Keel Ram", "short": "RAM", "cd": 11.0, "unlock": 69, "desc": "Charge like a hull through surf — slam every foe in a line for 1.5× ATK and drive them back."},
	"deadweight": {"name": "Deadweight", "short": "DWGT", "cd": 18.0, "unlock": 67, "desc": "Anchor the room — every foe on the floor staggers, stunned 1.5s."},
	"saltbomb": {"name": "Salt Bomb", "short": "BOMB", "cd": 13.0, "unlock": 65, "desc": "Hurl a fist of blessed salt ahead — the dead caught in it are blinded and slowed 3s."},
	"fogsong": {"name": "Fog Song", "short": "FOG", "cd": 18.0, "unlock": 63, "desc": "Sing the fog in — the dead lose your trail for 4s and your feet lighten +20%."},
	"broadside": {"name": "Broadside", "short": "BROAD", "cd": 15.0, "unlock": 61, "desc": "Loose the whole battery — a 90° volley before you for 1.0x ATK and a heavy shove."},
	"deadlight": {"name": "Deadlight", "short": "DEAD", "cd": 16.0, "unlock": 59, "desc": "A lantern flash that blinds the dead — all foes stunned 2.5s and grazed."},
	"dragline": {"name": "Dragline", "short": "DRAG", "cd": 14.0, "unlock": 57, "desc": "Hook the nearest foe and haul it to your blade — 1.2x ATK on arrival."},
	"keelsplit": {"name": "Keel Split", "short": "KEEL", "cd": 22.0, "unlock": 45, "desc": "Split the keel — a full-tile line ahead takes 1.4× ATK and drags slowed for 2s."},
	"anchordrop": {"name": "Anchor Drop", "short": "ANCH", "cd": 28.0, "unlock": 41, "desc": "Drop a spectral anchor — foes within 2 tiles take 1.6x ATK and are pinned in place for 2s."},
	"rites": {
		"name": "Reaper's Toll", "short": "RTOL", "cd": 34.0, "unlock": 21,
		"desc": "Ring the toll: awake foes below 25% HP die outright; the rest take 1x ATK.",
	},
}

const ORDER := ["dash", "whirl", "thunder", "warcry", "nova", "judge", "sunder", "chains", "storm", "mend", "rites", "seismic", "kingsfall", "lance", "gravestep", "tidecall", "snapjaw", "graveseal", "riptide", "soultithe", "anchordrop", "soulfall", "keelsplit", "bloodtide", "sealegs", "deadreckon", "becalm", "irontide", "dragline", "deadlight", "broadside", "fogsong", "saltbomb", "deadweight", "keelram", "hullsplinter", "crowsdive", "salvagehook", "riptidesnare", "saltward", "bilgesnare", "warpaint", "brinelash", "ghostnet", "saltmaw", "keelsplitter", "deckrupture", "deathknell", "tidesnatch", "kingstoll", "chumtoss", "netcast", "brinevolley", "saltwake", "choruscall", "deckwash", "hullkneel", "crowsnest", "stormflag", "shellup", "bilgesurge", "severline", "secondwind", "galewind", "keelhurl", "maelstrom", "deckflare", "wickdraw", "sirenscall", "bloodmark", "deadeye", "rigger", "saltskin", "ironwake", "brineward", "wakeveil", "keelbolt", "galepulse", "keelover", "sounddeep", "saltpall", "keelhaul", "belltoll", "dredge", "grimpress", "palemark", "greywake", "crestwake", "wakecut", "keelring", "fogcall", "sanctum", "saltmantle", "fathomward", "saltcrest", "greyreprieve", "deeppeal", "palewake", "greytoll", "whiteknell", "whitewake", "trenchtoll", "sessioncall", "edictcall", "fealtycall", "neapcall", "springcall"]


static func get_s(id: String) -> Dictionary:
	return DB[id]


static func is_unlocked(id: String, level: int) -> bool:
	return level >= int(DB[id]["unlock"])
